- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/helpers.rs
- src/lib.rs
> Add support for Txz archives

- src/bins.rs
- src/fetchers.rs
- src/fetchers/gh_crate_meta.rs
- src/fetchers/quickinstall.rs
- src/main.rs
That in turns means that every fetcher error is caught properly.
Also add fetcher check error to debug log.
Fixes #109
> Make fetcher creating infallible

- .github/workflows/rust.yml
- README.md
> Build for apple M1 and add it and other new builds to readme

- Cargo.lock
- Cargo.toml
- src/bins.rs
- src/drivers.rs
- src/main.rs
> Use tempfile over tempdir

- README.md
- src/main.rs
Based on original work by @Darunada in #70
> CLI overrides

- Cargo.lock
- Cargo.toml
- README.md
- src/bins.rs
- src/drivers.rs
- src/errors.rs
- src/fetchers.rs
- src/fetchers/gh_crate_meta.rs
- src/fetchers/quickinstall.rs
- src/helpers.rs
- src/lib.rs
- src/main.rs
Closes #113 
Fixes #127
Fixes #2
> Refactor for rich errors, split user abort and genuine error

- src/main.rs
> Fix parsing in `entry`: Use `std::env::args_os`

- Cargo.lock
- Cargo.toml
- src/drivers.rs
- src/fetchers.rs
- src/helpers.rs
- src/main.rs
And use newer `format!` syntax.
> Switch to edition 2021

- .github/workflows/ci.yml
- src/lib.rs
> Add new workflow ci and fix `test::parse_meta`

- src/fetchers/quickinstall.rs
So that it is run in concurrent or even in parallel with the
`remote_exists`.
> Run QuickInstall reporting using `tokio::spawn`

- .github/workflows/rust.yml
- ci-scripts/run_tests_unix.sh
- src/helpers/extracter.rs
> Improve CI: Make tracking down bug easier

- Cargo.lock
- Cargo.toml
> Rm unused dep `cargo_metadata`

- src/target.rs
> Fix and improve windows target detection: Support abi == "gnullvm'

- Cargo.lock
- Cargo.toml
- src/drivers/crates_io.rs
- src/fetchers.rs
- src/fetchers/gh_crate_meta.rs
- src/fetchers/quickinstall.rs
- src/helpers.rs
- src/main.rs
> Refactor: Rm global variable `helpers::Client`

- src/main.rs
> Refactor: Confirm only once and move all confirmations into `entry`

- src/errors.rs
- src/main.rs
Fixed https://github.com/ryankurte/cargo-binstall/pull/216#discussion_r924017154
> Forbid --manifest-path to used with batch installation

- src/binstall/install.rs
- src/metafiles/cvs.rs
- src/metafiles/v1.rs
- src/metafiles/v2.rs
> Refactor: Make appending to metafiles easier and fix their err handling

- src/errors.rs
- src/helpers.rs
- src/main.rs
Fixed https://github.com/ryankurte/cargo-binstall/pull/216#discussion_r924000588
> Fix: join err handling, unify it using `BinstallError`

- Cargo.lock
- Cargo.toml
- src/helpers.rs
- src/helpers/flock.rs
- src/metafiles/v1.rs
- src/metafiles/v2.rs
> Fix updating metafiles: Use file lock to fix race condition

- .github/workflows/build-and-integration-tests.yml
- .github/workflows/unit-tests.yml
- ci-scripts/compile-settings.jq
It's unmaintained: https://github.com/actions-rs/toolchain/issues/216
> Stop using actions-rs

- .github/workflows/build-and-integration-tests.yml
This lets us use caching much more efficiently in CI, to dramatic effects. Now _that's_ fast. (~8 minutes to ~3 minutes)
> Reconfigure CI cache with fallbacks

- src/main.rs
> Print out help when `crate_names` is empty

- .github/workflows/build.yml
- ci-scripts/compile-settings.jq
> Use `build-std` feature for release build to reduce binary size

- src/binstall/resolve.rs
> Fix `binstall::resolve`

- .github/workflows/integration.yml
> Rm `$HOME/.cargo` to test `cargo-binstall`

- src/binstall.rs
- src/binstall/install.rs
- src/main.rs
> Improve doc of cmdline option `log_level`, add `--quiet` and pass it to `cargo-install`

- ci-scripts/tests.sh
- src/bins.rs
- src/errors.rs
- src/helpers.rs
> Improve err msg when source is missing in `BinFile::install_bin`

- Cargo.lock
- crates/lib/src/bins.rs
- crates/lib/src/fetchers.rs
- crates/lib/src/fetchers/gh_crate_meta.rs
- crates/lib/src/fetchers/quickinstall.rs
- crates/lib/src/manifests/cargo_toml_binstall.rs
- crates/lib/src/manifests/cargo_toml_binstall/package_formats.rs
- crates/lib/src/ops/resolve.rs
Resolved #295 plus some minor optimization.
> Auto detect `pkg_fmt`

- .github/scripts/bitbucket-test-Cargo.toml
- .github/scripts/fake-cargo/cargo
- .github/scripts/gitlab-test-Cargo.toml
- .github/scripts/tests.sh
- crates/lib/src/fetchers/gh_crate_meta.rs
Followup of #296 , related to #311 
> Test default `pkg-url` for GitLab and BitBucket

- Cargo.toml
- crates/bin/Cargo.toml
- crates/bin/build.rs
- crates/bin/src/bin_util.rs
- crates/bin/src/lib.rs
- crates/bin/src/main.rs
- crates/detect-targets/build.rs
- [Print rerun-if-changed=build.rs in build.rs](https://github.com/cargo-bins/cargo-binstall/commit/fd70c5d2fe8a3e0dfb2d07b0197780fcc32587b8)
- [Optimize compile-time: Extract bin/src/lib.rs](https://github.com/cargo-bins/cargo-binstall/commit/c2d63a72f84b591536d2da39995a4b2095000ab1) this will enable "cargo-binstall (lib)" to be compiled in parallel to other deps
- [Set profile for build-override](https://github.com/cargo-bins/cargo-binstall/pull/320/commits/6fb417da7251b491bb6c0af49a92338ac2a967ce)
- Minor refactor
- [Handle Runtime::new err gracefully in run_tokio_main](https://github.com/cargo-bins/cargo-binstall/commit/20c381d6412a4be23b69685bf08a3b0787b6495a)
- [Avoid mixing eprintln and error in MainExit::report](https://github.com/cargo-bins/cargo-binstall/commit/79828aa9c18a67e90d …
> Optimize compilation time

- crates/bin/src/ui.rs
> Ignore `trust_dns` log output

- crates/bin/src/args.rs
- crates/bin/src/entry.rs
- crates/detect-targets/src/desired_targets.rs
- crates/detect-targets/src/lib.rs
> Change typeof `Args::targets` to `Option<Vec<String>>`

- crates/detect-targets/src/desired_targets.rs
- crates/detect-targets/src/lib.rs
> Fix doc of `desired_targets`

- .github/scripts/release-pr-template.ejs
- .github/workflows/release-pr.yml
- crates/bin/release.toml
Two little fixes:
- adds the crate name to the prose bit in the first line
- uses the correct tag in the code block
> Fix release PR template

- README.md
> Recommend taiki-e/install-action

- .github/scripts/tests.sh
- crates/bin/src/args.rs
- crates/bin/src/entry.rs
- crates/lib/src/helpers/remote.rs
> Deprecate --secure, enforce HTTPS

- crates/detect-targets/Cargo.toml
> Fix `documentation` field in `detect-targets/Cargo.toml`

- .github/scripts/tests.sh
> Fix `.github/scripts/tests.sh`: Fix testing for ugprading

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/helpers/jobserver_client.rs
- crates/lib/src/ops/install.rs
> Replace dep `jobserver` with `jobslot`

- crates/lib/src/fetchers/gh_crate_meta.rs
> Trim trailing slash from repo

- .github/workflows/release-pr.yml
Whoops! We need that to release...
> Update release-pr config

- crates/bin/Cargo.toml
That's stopping updates from working at the moment.
> Fix bin metadata

- README.md
- SUPPORT.md
> docs: fix grammatical error

- Cargo.lock
- crates/binstalk/Cargo.toml
Also update zstd to v0.11.2
Fixed #356 
> Use fork binstall-zip here for new features & updated deps

- crates/binstalk/src/bins.rs
- crates/binstalk/src/errors.rs
- crates/binstalk/src/fetchers.rs
- crates/binstalk/src/fetchers/gh_crate_meta.rs
- crates/binstalk/src/fetchers/quickinstall.rs
- crates/binstalk/src/helpers/tasks.rs
- crates/binstalk/src/ops/install.rs
- crates/binstalk/src/ops/resolve.rs
Fixed #372 
To ensure that the installation stage won't fail because of missing
binaries.
> Verify that `bin_files` exist in `resolve` stage

- README.md
> Avoid misleading confusion of `README.md`

- .github/dependabot.yml
> Enable dependabot for `Cargo.lock`

- Cargo.lock
- crates/binstalk/Cargo.toml
- crates/binstalk/src/drivers/crates_io/vfs.rs
- crates/binstalk/tests/parse-meta.rs
> Bump dep `cargo_toml` to v0.12.0

- .github/scripts/cargo-tomls/bitbucket-test-Cargo.toml
- .github/scripts/cargo-tomls/github-test-Cargo.toml
- .github/scripts/cargo-tomls/gitlab-test-Cargo.toml
- .github/scripts/tests.sh
- Cargo.lock
- crates/binstalk/Cargo.toml
> Fix/dep cargo_toml: Bump to v0.12.1

- crates/binstalk/src/bins.rs
- crates/binstalk/src/errors.rs
- crates/binstalk/src/ops/resolve.rs
> Check `source_file_path` to ensure it is valid

- crates/binstalk/src/bins.rs
- crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
- crates/binstalk/src/ops/resolve.rs
> Optimize `bins::BinFile`

- crates/binstalk/src/manifests/cargo_toml_binstall.rs
- crates/binstalk/src/ops/resolve.rs
> Optimize applying `PkgOverride`s into `PkgMeta`

- .github/scripts/cargo-tomls/bitbucket-test-Cargo.toml
- .github/scripts/cargo-tomls/github-test-Cargo.toml
- .github/scripts/cargo-tomls/github-test-Cargo2.toml
- .github/scripts/cargo-tomls/gitlab-test-Cargo.toml
- .github/scripts/tests.sh
- SUPPORT.md
- crates/binstalk/src/bins.rs
- crates/binstalk/src/fetchers/gh_crate_meta.rs
- crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
- crates/binstalk/src/manifests/cargo_toml_binstall/package_formats.rs
Fixed #423 and fixed #406
Also fixed one typo and improved the CI test.
> Improve auto discover

- crates/binstalk/src/bins.rs
> Add more to `possible_dirs`

- crates/binstalk/src/ops/resolve.rs
> Fix skipping optional dep: Skip fetcher if they provide 0 bin

- Cargo.lock
- crates/bin/Cargo.toml
- crates/bin/src/args.rs
- crates/binstalk/Cargo.toml
> Bump clap to v4.0.2

- crates/bin/src/args.rs
pkg-fmt, bin-dir and pkg-url.
Fixed #444 
> Allow batch installation with `cli_overrides`

- README.md
> docs: update `unsupported crates` guide

- Cargo.lock
- crates/binstalk/Cargo.toml
- crates/binstalk/src/helpers/remote.rs
> Impl retry for 503 and 429 status code in response

- crates/bin/src/bin_util.rs
- crates/bin/src/main.rs
> Fix `-V` behavior

- crates/bin/src/ui.rs
- crates/binstalk/src/bins.rs
- crates/binstalk/src/ops/install.rs
> Fix clippy error on unit test CI

- .github/workflows/build.yml
- .github/workflows/unit-tests.yml
> Re enable `CARGO_UNSTABLE_SPARSE_REGISTRY`

- crates/binstalk/src/bins.rs
- crates/normalize-path/src/lib.rs
> Fix crate `normalize-path`

- Cargo.lock
- crates/binstalk/Cargo.toml
> Switch back from binstall-zip to zip

- .github/dependabot.yml
> Enable dependabot for binstalk-manifests

- README.md
> Mention upgrade, fix #514

- crates/bin/src/args.rs
> Short option for no-confirm flag

- crates/detect-targets/src/detect.rs
- crates/detect-targets/src/detect/macos.rs
> detect-targets: Add support of MacOS universal binary 

- .github/workflows/build.yml
- .github/workflows/release.yml
- README.md
> Create universal binary for MacOS in workflow release

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
- crates/binstalk-manifests/Cargo.toml
- crates/binstalk-types/Cargo.toml
- crates/binstalk/Cargo.toml
- bytes v1.2.1 => v1.3.0
- serde_json v1.0.88 => v1.0.89
- compact_str v0.6.0 => v0.6.1
> Upgrade dependencies

- crates/bin/build.rs
> Fix crates/bin/build.rs: Rerun build.rs if manifest.rc and windows.manifest changed

- crates/bin/src/ui.rs
> Fix panic in `ui::confirm` on I/O error

- crates/bin/src/logging.rs
instead of exiting the entire process.
> Fix logging: Print error and continue on failure to flush logs

- crates/binstalk/src/errors.rs
> Fix `BinstallError::CrateContext`: Forward diagnostics of field `CrateContextError::err`

- crates/binstalk-manifests/src/cargo_crates_v1.rs
Avoid calling `CrateVersionSource::from_str` which parses the source and allocates `Url`.
> Optimize `CratesToml::collect_into_crates_versions`

- .github/scripts/pack-release-archives.sh
> Optimize pre-built artifact size: Set compression level for `zip` to 9 (max)

- crates/binstalk-manifests/src/cargo_crates_v1.rs
Also add a new unit test for this bug.
Fixed #621
> Fix `CratesToml::load_from_reader`: Ret default for empty reader

- crates/binstalk-manifests/src/cargo_crates_v1.rs
> Impl new fn `CratesToml::append_to_file`

- crates/detect-targets/src/detect.rs
> Verify target triple retrieved from `rustc` is valid

- crates/binstalk/src/fetchers/quickinstall.rs
> Update quickinstall url

- crates/detect-targets/Cargo.toml
- crates/detect-targets/src/detect.rs
- crates/detect-targets/src/detect/macos.rs
- crates/detect-targets/src/detect/windows.rs
* Enable dep guess_host_triple for any non-linux OS
* Refactor: Rm `{windows, macos}::detect_target_*`
* Refactor `detect_targets`
> Refactor `detect-targets`

- crates/binstalk-downloader/src/download.rs
- crates/binstalk/src/errors.rs
> Rm unused variant `binstalk_downloader::download::DownloadError::UserAbort`

- crates/binstalk-downloader/src/remote.rs
> Fix `Client::new`: Make sure we use at least tls 1.2

- Cargo.lock
- crates/binstalk/Cargo.toml
- crates/binstalk/src/ops/resolve.rs
> Optimize `resolve_inner`: Avoid `VersionReq::clone`

- .github/workflows/ci.yml
- .github/workflows/release-build.yml
- justfile
Fixes #661 
Also contains disabled settings for #662 and #663
> Try build-std with arm64 gnu

- Cargo.lock
> Update transitive deps

- .github/workflows/release-build.yml
It's unclear whether softprop's does that... https://github.com/softprops/action-gh-release/issues/269
> Use release action with explicit support for being called multiple times

- justfile
> Recurse when packaging for mac

- crates/bin/src/entry.rs
- e2e-tests/strategies.sh
> Fix `FileLock` for `.crates.toml` not dropped

- crates/detect-targets/src/detect.rs
Fixed #704 
On Alpine, rustc returns host triple `x86_64-alpine-linux-musl`, so we have to adopt code from
[`convert_custom_linux_target`](https://github.com/crossbeam-rs/crossbeam/blob/5519aeb5c2156c5aff9a88d41dcfbcd838e9a1ea/build-common.rs#L1-L13) to fix this.
> Fixed #704: Fix `get_target_from_rustc` for alpine

- Cargo.lock
- crates/binstalk/Cargo.toml
- crates/binstalk/src/bins.rs
- crates/binstalk/src/fs.rs
- e2e-tests/self-upgrade-no-symlink.sh
- justfile
> Fix self-update on windows

- justfile
> Enable `mir-opt-level=4` for release

- crates/binstalk-manifests/src/cargo_crates_v1.rs
> Fix unused import in binstalk-manifests

- crates/bin/Cargo.toml
- justfile
> Enable feature `zstd-thin` by default

- justfile
> Disable backtrace support from miette in release/CI build

- crates/binstalk-downloader/src/download.rs
- crates/binstalk-downloader/src/remote.rs
- crates/binstalk-manifests/src/binstall_crates_v1.rs
- crates/binstalk-manifests/src/cargo_crates_v1.rs
- crates/binstalk-manifests/src/cargo_crates_v1/crate_version_source.rs
- crates/binstalk/src/errors.rs
> Improve `fmt::Display` impl for all Error types

- crates/bin/Cargo.toml
- crates/bin/src/args.rs
> Read `log_level` from env `CARGO_BINSTALL_LOG_LEVEL` if arg not present

- .github/workflows/release-build.yml
> Add step to relase-build to make sure it's runnable

- crates/bin/Cargo.toml
- crates/bin/src/args.rs
Reverts cargo-bins/cargo-binstall#790
> Revert "Read `log_level` from env `CARGO_BINSTALL_LOG_LEVEL` if arg not present"

- crates/bin/src/args.rs
> Document environment variable `BINSTALL_LOG_LEVEL`

- .github/workflows/ci.yml
- .github/workflows/release-build.yml
- justfile
> Use `cargo-zigbuild` for cross compilation

- crates/bin/src/entry.rs
- crates/binstalk-downloader/src/remote.rs
- crates/binstalk-downloader/src/remote/certificate.rs
> Support adding root cert via env `CARGO_HTTP_CAINFO`, `SSL_CERT_{FILE, PATH}`

- crates/bin/src/args.rs
> Inc default interval in `--rate-limit` to 10ms

- justfile
> Enable icf=safe & use rust-lld for targets other than win

- .github/workflows/ci.yml
No point in rebuilding if only the markdown is changed.
> Ignore README.md and SUPPORT.md in workflow "ci"

- SUPPORT.md
> Update SUPPORT.md on `bin-dir` default

- justfile
> Enable `-Z share-generics` to reduce compilation time

- crates/binstalk/src/fetchers.rs
- crates/binstalk/src/fetchers/gh_crate_meta.rs
- crates/binstalk/src/ops/resolve.rs
So that we don't have to create multiple HEAD/GET http request to get the final, redirected url.
> Optimize `GhCrateMeta::find`: Cache url resolution result

- .github/workflows/release-build.yml
- justfile
> Switch to `cargo-zigbuild` for `aarch64-unknown-linux-gnu` and `x86_64-unknown-linux-musl`

- .github/workflows/ci.yml
- justfile
> Fix CI: Only turn on feature pkg-config on linux and fix cross compilation

- crates/bin/src/args.rs
- crates/bin/src/entry.rs
- crates/binstalk/src/ops.rs
- crates/binstalk/src/ops/resolve/resolution.rs
> Add new option `--locked` that is passed through to `cargo-install`

- e2e-tests/other-repos.sh
> Disable GitLab e2e-test due to them deleting my account & repo

- .github/actions/just-setup/action.yml
- .github/workflows/release-build.yml
> Fix use of `hashFiles` in `key` of bulid-cache

- crates/bin/src/entry.rs
- crates/binstalk/src/ops.rs
- crates/binstalk/src/ops/resolve/resolution.rs
> Fix: Pass value of `--roots` to `cargo-install` as `--root`

- crates/binstalk-downloader/src/gh_api_client.rs
> Verify syntax of the github token provided in `GhApiClient::new`

- .github/workflows/ci.yml
- .github/workflows/release-build.yml
Newly out from 1.68.0! https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html
> Use stable sparse registry option

- crates/bin/src/args.rs
> Read from env `GH_TOKEN` for github_token as a fallback

- .github/workflows/ci.yml
> Add job windows-aarch64-check to workflow ci

- crates/bin/src/args.rs
- crates/bin/src/git_credentials.rs
- crates/bin/src/lib.rs
> Clarify git credential code and fix infinite loop bug

- crates/binstalk-downloader/src/download/async_extracter.rs
- crates/binstalk/src/ops/resolve.rs
> Fix `extract_tar_based_stream`: Normalize path before adding them to `ExtractedFiles`

- crates/bin/src/entry.rs
- crates/binstalk/src/drivers/crates_io.rs
- crates/binstalk/src/ops.rs
- crates/binstalk/src/ops/resolve.rs
Fixed https://github.com/taiki-e/install-action/issues/89
> Obey crates.io crawler policy: Only make one request per sec

- .github/workflows/cache-cleanup.yml
As suggested here: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches
> Cleanup caches for closed PRs

- crates/bin/src/install_path.rs
- crates/binstalk-manifests/src/cargo_config.rs
- crates/binstalk-manifests/src/lib.rs
> Use `install.root` in `$CARGO_HOME/config.toml`

- crates/detect-targets/src/detect/macos.rs
> Add alias `universal2-apple-darwin` to `universal-apple-darwin`

- crates/binstalk-downloader/src/remote.rs
> Retry http request on connection error

- Cargo.lock
> Bump transtive deps

- Cargo.lock
> Bump transitive deps using `cargo update --aggressive`

- Cargo.lock
- crates/binstalk-types/src/cargo_toml_binstall/package_formats.rs
- crates/binstalk/Cargo.toml
- crates/binstalk/src/bins.rs
- crates/binstalk/src/errors.rs
- crates/binstalk/src/fetchers/gh_crate_meta.rs
- crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
- crates/binstalk/src/ops/resolve.rs
- crates/leon/src/lib.rs
- crates/leon/src/macros.rs
- crates/leon/src/parser.rs
- crates/leon/src/template.rs
- crates/leon/src/values.rs
> Use leon for template in binstalk & detect malformed pkg-url/pkg-fmt early

- .github/workflows/release-build.yml
> Speedup workflow lipo in `release-build.yml`

- .github/workflows/release-build.yml
- justfile
> Optimize `release-build.yml`: Avoid building benchmark dependencies

- crates/binstalk-manifests/src/cargo_crates_v1.rs
> feat: pretty print .crates.toml manifest to match cargo behaviour

- crates/binstalk-downloader/Cargo.toml
> Add comment to `src/binstalk-downloader/Cargo.toml`

- justfile
> Test building doc in `ci.yml`/lint

- crates/bin/Cargo.toml
- justfile
> Add & Enable new feat `log_max_level_debug` to speedup debug build

- .github/dependabot.yml
> dependabot: Update deps of direct deps & simplify config

- Cargo.toml
> Simplify `profile` overrides in `Cargo.toml` using `inherits`

- .github/workflows/release-build.yml
- justfile
> Include `cargo-timings` report in release build

- .github/workflows/ci.yml
> Fallback to pull_request num or commit sha if `github.ref` is not available

- e2e-tests/live.sh
- e2e-tests/manifest-path.sh
- e2e-tests/other-repos.sh
- e2e-tests/strategies.sh
- e2e-tests/subcrate.sh
and also test `fetch_crate_cratesio_version_matched` in `e2e-tests/live.sh`.
> e2e-tests: Check version of installed crates

- crates/binstalk-downloader/src/gh_api_client.rs
- crates/binstalk-downloader/src/gh_api_client/request.rs
> `GhApiClient`: Fallback to unauthorized mode if auth token is invalid

- .github/workflows/upgrade-transitive-deps.yml
> Set `upgrade-transitive-deps.yml` to run on every Fri

- rust-toolchain.toml
> Add `rust-toolchain.toml`

- crates/bin/src/args.rs
Ref https://github.com/oeb25/binswap/issues/2
> Show license and source in long help

- .github/workflows/release-pr.yml
before creating the release PR.
> ci: Check package publish in `release-pr.yml`

- .github/workflows/release-build.yml
> fix `release-build.yml`: Explicitly set release_name to the same as tag

- .github/workflows/release-build.yml
Set `CARGO_*` env before caching is done.
> fix `release-build.yml`: Fix cache key for `Swatinem/rust-cache@v2`

- crates/bin/Cargo.toml
- crates/binstalk/Cargo.toml
> Fix GPL-3.0 license identifier

- crates/binstalk-downloader/src/gh_api_client/request.rs
When installing `cargo-expand` v1.0.59, I got an error message:
```
Failed to parse http response body as Json: invalid type: null, expected a string at line
1 column 90
```
This is because `GraphQLPageInfo::end_cursor` can actually be `null`, so I change its type to `Option<CompactString>`.
> fix `binstalk_downloader::GhApiClient` json deser error

- crates/bin/src/entry.rs
- crates/binstalk-manifests/src/cargo_config.rs
> Fix loading `.cargo/config.toml`

- crates/binstalk/src/fetchers/quickinstall.rs
Fixed #1222 by fetching lists of supported targets from quickinstall repository.
> Fix failure to send quickinstall report

- crates/detect-targets/src/detect/macos.rs
Fallback to `x86_64h-apple-darwin` if supported.
> detect-targets: Add fallback to x86_64-apple-darwin

- crates/binstalk/Cargo.toml
To support new target x86h-apple-darwin
> Bump dep target-lexicon to v0.12.11

- .github/workflows/release-build.yml
- justfile
> CI: Add release build for x86_64h-apple-darwin

- crates/binstalk/src/fetchers.rs
- e2e-tests/subcrate.sh
> Fix subcrate resolution for `wasm-bindgen-cli`

- crates/bin/src/args.rs
- crates/binstalk/src/drivers.rs
- crates/binstalk/src/drivers/registry.rs
- crates/binstalk/src/helpers.rs
- crates/binstalk/src/lib.rs
To reduce amount of breaking changes.
> Reduce public interface of `binstalk`

- .github/workflows/release-pr.yml
for `binsalk-downloader` since its feature `http3` require this.
> Fix `release-pr.yml`: Set `RUSTFLAGS=--cfg reqwest_unstable`

- Cargo.lock
Update transitive dependencies for patch release.
> dep: Upgrade transitive dependencies

- crates/atomic-file-install/src/lib.rs
Do not panic if path does not have a parent, instead return an error.
> Fix panic in `atomic-file-install`

- .github/dependabot.yml
- .github/workflows/release-pr.yml
- crates/binstalk-bins/LICENSE
and also add missing `crates/binstalk-bins/LICENSE`
> Update CI & dependabot: Add new crates

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
> dep: Bump reqwest to v0.11.19

- crates/binstalk-downloader/src/download.rs
To make sure the `data_verifier` consumes the entire file and produces the correct checksum.
> Fix `binstalk_downloader::Download` for data-verifier

- crates/binstalk-fetchers/Cargo.toml
- crates/binstalk-fetchers/src/common.rs
- crates/binstalk-fetchers/src/lib.rs
- crates/binstalk-fetchers/src/quickinstall.rs
- crates/binstalk-registry/Cargo.toml
- crates/binstalk/Cargo.toml
Also fixed `package.metadata.docs.rs` for `binstalk-registry`.
> binstalk-fetchers: Add feature quickinstall

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
> dep: Rm unused dep `generic-array` in `binstalk-downloader`

- crates/binstalk-registry/src/common.rs
- crates/binstalk/src/ops/resolve.rs
- crates/leon/src/template.rs
This PR needs to be approved and merged before any other PR can be merged.
> Fix clippy lint and format

- crates/binstalk-downloader/src/remote.rs
- crates/binstalk-registry/src/common.rs
- crates/binstalk-registry/src/crates_io_registry.rs
- crates/binstalk-registry/src/git_registry.rs
- crates/binstalk-registry/src/sparse_registry.rs
> feat: Add more logging to `binstalk-{downloader, registry}`

- .github/FUNDING.yml
I'm feeling guilty for only adding myself to the list of sponsorship
> Add GitHub sponsor for maintainer NobodyXu

- crates/binstalk-fetchers/src/gh_crate_meta.rs
- crates/binstalk-fetchers/src/quickinstall.rs
- crates/binstalk-types/src/cargo_toml_binstall.rs
- crates/binstalk/src/ops/resolve.rs
- e2e-tests/signing.sh
Hardcodes the quickinstall public key
> Check quickinstall signatures

- SIGNING.md
To make sure our user can setup signing without problem.
> Doc: Provide solutions for common problems encountered during signing

- crates/binstalk-downloader/src/gh_api_client.rs
Fixed #1414
There are many different kinds of gh tokens and they can change the format at anytime, so we can't check it based on its formats.
> Fix `GhApiClient`: Accept any `auth_token` given

- crates/binstalk-downloader/src/remote/resolver.rs
> Downgrade DNS info! to debug!

- .github/actions/just-setup/action.yml
- .github/workflows/ci.yml
- .github/workflows/release-packages.yml
- justfile
This is the last version that worked in our CI
> Fix CI: Use `cargo-hack` 0.6.10

- crates/fs-lock/src/lib.rs
In certain situations it's useful to attempt to lock the file.
> feat(fs-lock): new_try_exclusive and new_try_shared

- .github/workflows/ci.yml
- .github/workflows/release-cli.yml
- .github/workflows/release-packages.yml
> build(deps): bump actions/{up, down}load-artifact from 3 to 4

- .github/workflows/ci.yml
- .github/workflows/release-cli.yml
- .github/workflows/release-packages.yml
Reverts cargo-bins/cargo-binstall#1533 to fix #1554
> Revert "build(deps): bump actions/{up, down}load-artifact from 3 to 4"

- crates/bin/src/args.rs
- crates/bin/src/bin_util.rs
- crates/bin/src/entry.rs
- crates/binstalk/src/errors.rs
- crates/binstalk/src/ops/resolve/resolution.rs
- e2e-tests/continue-on-failure.sh
- e2e-tests/live.sh
- justfile
> feat: Impl new option `--continue-on-failure`

- crates/binstalk-downloader/src/download.rs
Fixed #1575
Always consume the stream if a `data_verifier` is provided in `binstalk_download::Download`
> Fix Unmatched checksum error

- Cargo.lock
- crates/detect-targets/Cargo.toml
- crates/detect-targets/src/detect/windows.rs
> Remove dep windows-dll and replace it with manual loading

- crates/binstalk-downloader/src/remote.rs
- crates/binstalk-git-repo-api/src/gh_api_client.rs
- crates/binstalk-git-repo-api/src/gh_api_client/common.rs
- Mv logic into `binstalk_downloader`
- Check for `RETRY_AFTER` and `x-ratelimit-remaining` on any status code
> Fix rate limit checking in `GhApiClient`

- .github/workflows/ci.yml
- crates/binstalk-git-repo-api/src/gh_api_client.rs
- justfile
Fixed #1727
Also change client-side rate limit for `binstalk-gh-api-client` to 1 request per 200 ms.
> Speedup ci: Only run tests on change

- .github/workflows/ci.yml
- .github/workflows/release-packages.yml
> Fix job `changed-files`

- .github/workflows/release-packages.yml
- .github/workflows/upgrade-transitive-deps.yml
- [Run e2e-test on x86_64h-apple-darwin](https://github.com/cargo-bins/cargo-binstall/commit/32bd1964c10cc2d95a113b33f6518e54c5b21a1a)
- [Fix upgrade-transitive-deps](https://github.com/cargo-bins/cargo-binstall/commit/c36b8b1dbddf3e50c1f4733731f0efb612793ca8)
> Improve ci

- crates/binstalk-downloader/src/download.rs
- crates/binstalk-downloader/src/remote.rs
- crates/binstalk-downloader/src/remote/resolver.rs
- crates/binstalk-fetchers/src/lib.rs
- crates/binstalk-git-repo-api/src/gh_api_client.rs
- crates/binstalk-git-repo-api/src/gh_api_client/repo_info.rs
- crates/binstalk-registry/src/common.rs
- crates/binstalk-registry/src/crates_io_registry.rs
- crates/binstalk-registry/src/git_registry.rs
- crates/binstalk-registry/src/sparse_registry.rs
> Improve derbugg logging

- .github/workflows/ci.yml
> Fix passing GITHUB_TOKEN in ci.yml

- .github/workflows/ci.yml
> Fix job changed-files ci.yml

- crates/bin/src/entry.rs
- crates/bin/src/gh_token.rs
> Improve gh token auto scraping

- .github/workflows/upgrade-transitive-deps.yml
> Fix upgrade-transitive-deps.yml

- install-from-binstall-release.sh
> Fix install-from-binstall-release.sh

- .github/workflows/upgrade-transitive-deps.yml
> Fix missing ' upgrade-transitive-deps.yml

- .github/workflows/release-pr.yml
> Fix release-pr.yml

- crates/bin/src/args.rs
> Add env var BINSTALL_NO_DISCOVER_GITHUB_TOKEN

- .github/workflows/ci.yml
Dry run publish in merge_queue CI for release PR
> Fix release-dry-run

- crates/binstalk-downloader/Cargo.toml
> Fix docs.rs build of binstalk-downloader

- .github/workflows/release-pr.yml
> Bump cargo-bins/release-pr from 2.1.1 to 2.1.2

- .github/workflows/release-pr.yml
Stupid mistakes introduced in #1789
> Fix typo in release-pr.yml inputs

- .github/workflows/gh-action.yml
> Speedup and prevent rate limit in gh-action.yml

- README.md
> Fix url link in README.md

- Cargo.lock
- crates/binstalk-manifests/src/cargo_crates_v1.rs
- crates/binstalk-manifests/src/cargo_crates_v1/crate_version_source.rs
- crates/binstalk-registry/src/git_registry.rs
- crates/binstalk-registry/src/lib.rs
- crates/binstalk-registry/src/sparse_registry.rs
- crates/binstalk/Cargo.toml
- crates/binstalk/src/ops/resolve.rs
- crates/binstalk/src/ops/resolve/resolution.rs
- e2e-tests/git.sh
- e2e-tests/manifest-path.sh
- e2e-tests/registries.sh
> Fix v1 manifest format for git and local path

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
> Enable vendored native-tls if native-tls and static is enabled

- crates/binstalk-manifests/src/cargo_config.rs
- crates/cargo-toml-workspace/src/lib.rs
> Fix 1.80 cargo clippy errors

- crates/bin/src/args.rs
> Add env for --disable-strategies

- .github/workflows/ci.yml
- .github/workflows/gh-action.yml
- .github/workflows/install-script.yml
- .github/workflows/release-packages.yml
macos-latest is now an alias of macos-14 M1
> Switch back to macos-latest

- crates/bin/src/args.rs
- crates/bin/src/entry.rs
- crates/binstalk/Cargo.toml
- crates/binstalk/src/ops.rs
- crates/binstalk/src/ops/resolve.rs
> Add `--maximum-resolution-timeout`

- SUPPORT.md
- crates/bin/src/args.rs
- crates/binstalk-types/src/cargo_toml_binstall.rs
- e2e-tests/manifests/strategies-test-Cargo2.toml
- e2e-tests/strategies.sh
> feature: Merge disable strategies

- release-plz.toml
Set git_release_latest=false in workspace
> Fix release-plz.toml

- crates/binstalk-downloader/src/remote/resolver.rs
Ported from seanmonstar/reqwest#2378
> Enable happy eyeballs when using hickory-dns

- .github/workflows/release-cli.yml
Using [gh-release-edit](https://cli.github.com/manual/gh_release_edit)
> Fix setting release to latest in release-cli.yml

- SUPPORT.md
> Add link for all supported pkg-fmt in SUPPORT.md

- .github/actions/just-setup/action.yml
- Exclude workspace from macOS SIP and windows defenders
> Speedup ci: Exclude workspace from macOS SIP and windows defenders

- crates/binstalk-fetchers/src/quickinstall.rs
> Improve quickinstall telemetry failure message

- crates/bin/src/args.rs
This makes it easier to integrate with cargo-make
> allow setting no_confirm via envvar

- .github/workflows/ci.yml
Make sure we have up-to-date cache.
> CI: Run ci.yml on every Sat

- README.md
- crates/bin/src/ui.rs
The default is clarified, and actually implemented.
> Yes/NO defaults to "no" when just enter is pressed

- .github/actions/just-setup/action.yml
- make sure the right target is pass to install-action, just in case there's no available binary
- configure THP/malloc at the start of action
> CI: Fix just-setup

- .github/workflows/ci.yml
> Run CI on main whenever dependencies have changed

- .github/workflows/release-pr.yml
It needs permission pull-request to create PR
> Fix permission of release-pr.yml

- .github/workflows/upgrade-transitive-deps.yml
> Fix creating PR in upgrade-transitive-deps.yml

- crates/binstalk-downloader/Cargo.toml
- crates/binstalk-downloader/src/remote/resolver.rs
> Upgrade hickory-resolver to 0.25.0-alpha.5

- .github/workflows/release-pr.yml
We only want to use it for cargo-binstall release
> Simplify release-pr.yml

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
Use rust libbz2 impl
p.S. I plan to submit more PRs tomorrow
> Use bzip2/libbz2-rs-sys

- crates/detect-targets/src/detect/linux.rs
Android does not have `-unknown-` in target and alpine uses `-alpine-` instead of `-unknown-`, so the musl fallback must be taken special care when generating
Fix #1057
> Fix detect-targets musl fallback for android and alpine

- .github/workflows/ci.yml
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> security: pin tj-actions/changed-files to a non-compromised commit

- Cargo.lock
- crates/binstalk-downloader/Cargo.toml
- crates/binstalk-downloader/src/remote/resolver.rs
> dep: Bump hickory-resolver to 0.25.1

- .github/workflows/release-packages.yml
- justfile
- zigbuild-requirements.txt
to fix the erorr in https://github.com/cargo-bins/cargo-binstall/actions/runs/14797824334/job/41549189656?pr=2137
> Bump ziglang to latest version

- install-from-binstall-release.sh
> Add --retry 10 to curl call in install-from-binstall-release.sh

- crates/bin/src/args.rs
- crates/bin/src/entry.rs
- crates/binstalk/src/ops.rs
- crates/binstalk/src/ops/resolve/resolution.rs
- e2e-tests/specific-binaries.sh
- justfile
Fixes https://github.com/cargo-bins/cargo-binstall/issues/1961.
This seems straightforward, but feel free to let me know if you'd like any changes.
Thanks!
> Add a `--bin` argument to mirror `cargo install --bin`.

- .github/actions/just-setup/action.yml
> ci: enable cache-workspace-crates

- README.md
Forgot to update and mentioned in #2213
> Update quickinstall stats url in README.md

- .github/actions/just-setup/action.yml
> Fix cache-workspace-crates in action.yml

- .github/workflows/release-packages.yml
- crates/binstalk-git-repo-api/src/gh_api_client.rs
> Disable unnecessary testing breaking ci

- .github/workflows/release-cli.yml
- .github/workflows/release-plz.yml
https://blog.rust-lang.org/2025/07/11/crates-io-development-update-2025-07/
> Use crates.io trusted publishing

- crates/detect-targets/Cargo.toml
- crates/detect-targets/src/desired_targets.rs
> Fix race condition of DesiredTargets

- .github/workflows/ci.yml
- .github/workflows/release-packages.yml
Use native support instead of cross compilation
> ci: Use windows-11-arm for arm windows build

- e2e-tests/specific-binaries.sh
by using official artifacts now quickinstall is done
> ci: speedup taplo-cli installation in specific-binaries.sh

- .github/actions/just-setup/action.yml
- e2e-tests/live.sh
- e2e-tests/signing.sh
- e2e-tests/specific-binaries.sh
since it's currently down due to maintenance of a suspicious malware
> ci: disable quickinstall test in signing.sh

- crates/bin/src/args.rs
Additional context: https://github.com/cargo-bins/cargo-binstall/issues/2259
> clarify --install-path behavior when installing from source
