cargo-bins/cargo-binstall

README.md
how's this @Firstyear? (thanks for the feedback!)
=> re-work readme, add examples for william

Cargo.lock, Cargo.toml, README.md, build.rs, src/bins.rs, src/drivers.rs, src/fetchers.rs, src/fetchers/gh_crate_meta.rs, src/fetchers/gh_release.rs, src/fetchers/quickinstall.rs, src/helpers.rs, src/lib.rs, src/main.rs
See this issue: https://github.com/alsuren/cargo-quickinstall/issues/27
Quick Install is a hosted repo of built crates, essentially. The approach I've taken here is a list of strategies:
1. First, we check the crate meta or default and build the URL to the repo. Once we have that, we perform a `HEAD` request to the URL to see if it's available.
2. If it's not, we build the URL to the quickinstall repo, and perform a `HEAD` to there.
As soon as we've got a hit, we use that. I've built it so it's extensible with more strategies (e.g. for #4)
=> QuickInstall support

Cargo.toml, README.md, src/bins.rs, src/fetchers/gh_crate_meta.rs, src/lib.rs
This from feedback in #19:
> wrt. [bin-dir](https://github.com/ryankurte/cargo-binstall/blob/8af4f2c5ea955ca8808358e64594b6e903aaa68c/src/lib.rs#L72) and bin-path, this appears to be a typo / should all be called bin-dir
This is only a readme fix afaict, I changed all occurences of `bin-path` in there to `bin-dir`.
> wrt. format, those are actually two (unfortunately named) different concepts, the first refers to the archive format (eg. .tgz), the second to the binary format (which needs a .exe appended for windows).
This introduces two new substitutions:
- `binary-ext` is the old "`format` in `bin-dir`"
- `archive-format` is the old "`format` in `pkg-url`"
Contents are unchanged: `binary-ext` includes the dot, `archive-format` doesn't. That makes it easy to upgrade and also personally I …
=> Split {format} and allow use of {binary-ext} in pkg-url

src/bins.rs
I was intending to keep #103 as a draft but Ctrl-Entered by accident. Anyway, after:
```
testpsko@tarta:~/cargo-binstall$ ./target/debug/cargo-binstall binstall radio-sx128x
15:28:48 [INFO] Installing package: 'radio-sx128x'
15:28:49 [INFO] Checking for package at: 'https://github.com/rust-iot/rust-radio-sx128x/releases/download/v0.17.2/sx128x-util-x86_64-unknown-linux-gnu.tgz'
15:28:50 [INFO] The package will be downloaded from github.com
15:28:50 [INFO] Downloading package from: 'https://github.com/rust-iot/rust-radio-sx128x/releases/download/v0.17.2/sx128x-util-x86_64-unknown-linux-gnu.tgz'
15:28:52 [INFO] This will install the following binaries:
15:28:52 [INFO]   - sx128x-util (sx128x-util-x86_64-unknown-linux-gnu -> /home/testpsko/.cargo/bin/sx128x-util-v0.17.2)
15:28:52 [INFO] And …
```
=> Point links to just basename-ver, print them the right way 'round

src/bins.rs
On windows, but also use templating to render it correctly everywhere.
Fixes #106
On reflection, this is probably also a better fix for #111 than #115
=> Use the correct link name

Cargo.lock, Cargo.toml, src/bins.rs, src/main.rs
Fixes #113
Did both:
- Help message is fixed up to mention that it's the same syntax/semantics as a Cargo.toml version field
- When using `--version 1.2.3` and the version resolves to something different, warn and reconfirm.
=> Clarify --version usage and add a warning at runtime

Cargo.lock, Cargo.toml, src/main.rs
If all the fetchers (currently only direct from meta and quickinstall) fail, prompt to install from source and then do so via calling `cargo install`.
Closes #108
=> Fallback to installing from source

src/drivers.rs
This should do the trick for #113 to ignore yanked versions. Filtering these out just before finding a matching version
=> fix: ignore crate version if yanked

src/main.rs
This should fix the case for #113 where `--no-confirm` or `--dry-run` just continues to install
=> fix: abort install for specific version if not confirmed

Cargo.lock, Cargo.toml
I favor `rustls` over `openssl` and this project already uses `rustls` with its `reqwest` clients, `crates_io_api` has a feature to enable `rustls`.
=> feat: use rustls for crates_io_api

Cargo.lock, Cargo.toml, src/drivers.rs
This will remove the `crates-index` dependency, in favor of using the information already provided via `crates_io_api`.
Another step in reducing the need for `openssl-sys` and may provide a way to install binaries on OSs such as `alpine` without git or cargo.
It's a draft as it will collide with changes such as #122
=> feat: remove crates-index dependency

.github/workflows/rust.yml
Add musl target which provides prebuilt binaries statically linked with musl libc and does not depend on any dynamic
library, thus can be run anywhere.
I've verified that for `x86_64`, the binary built by job `build` does not contain any dynamic dependency and can work in ubuntu container and I also added it to job `test`, though it currently failed to build `cargo-binstall` as v0.7.0 requires openssl, but will be automatically fixed once a new release is made.
I also added target `aarch64` with both glibc and musl libc.
~~The `arm-linux-musleabihf-gcc` on the other hand is missing on arm build and I don't know how to fix this.~~
Fixed by using `use-cross: true`.
=> Add more targets for prebuilt binaries

.github/workflows/rust.yml, Cargo.toml
by enabling lto, setting `codegen-units` to 1 and setting panic behavior
to `abort`.
On my `aarch64-apple-darwin` with `rustc 1.61.0`, this reduces the size
of binary from `7.8M` to `4.9M`.
Edit:
With `RUSTFLAGS=-Zstrip=symbols`, I was able to further reduce the size of binary to `3.8M` on my Macbook Air.
=> Optimize release build

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, Cross.toml, README.md, src/helpers.rs, src/lib.rs
=> feat: Add `zstd` support

Cargo.lock, Cargo.toml
- Optimize dep tokio: Disable all feature except rt-multi-thread, macros and process
- [Disable all features of zip except deflate, bzip2 and zstd](https://github.com/ryankurte/cargo-binstall/commit/4e53c66a8c8911e32129986faa612135c6a117a0)
- Use [`zlib-ng`], the fastest backend `flate2` supported
[`zlib-ng`]: https://github.com/zlib-ng/zlib-ng
=> Optimize dependencies

src/fetchers/gh_crate_meta.rs, src/fetchers/quickinstall.rs, src/helpers.rs
Only to convert it back to `Url` in `helpers::remote_exists`
=> Optimize `GhCrateMeta::check`: Avoid converting url to str

src/main.rs
Using `rt.block_on`, the future returned by `entry()` can only be run on
the main thread.
Buf if we use `tokio::spawn`, then it can be run on any thread.
=> Spawn `entry()` in `main` to improve parallelism

src/fetchers.rs, src/fetchers/gh_crate_meta.rs, src/fetchers/quickinstall.rs, src/main.rs
This is a draft PR demonstrating how we can support checking for multiple targets, it seems to be much easier than I thought.
Due to #157 being pending, I decided to not touch cmdline parsing at all and let #157 decides how we should handle `--target` since now we supports multiple targets.
=> Support for checking multi-targets

Cargo.lock, Cargo.toml, ci-scripts/run_tests_unix.sh, src/fetchers/quickinstall.rs, src/helpers.rs, src/helpers/tls_version.rs, src/main.rs
This PR adds new command line option:
- `--https-only-mode`
- `--min-tls-version [tls1-2, tls1-3]`
I added this since [taiki-e/install-action] requires https only and tls to be at least `1.2`.
[taiki-e/install-action]: https://github.com/taiki-e/install-action
=> Feature: Support https only mode and min tls version

src/drivers/crates_io.rs, src/drivers/crates_io/visitor.rs, src/helpers.rs, src/helpers/async_extracter.rs, src/main.rs
The following steps are moved into `block_in_place` mode:
- `main.rs:448`: "Install binaries"
- `load_manifest_path`: which performs file reading and `std::fs::read_dir`
- `ManifestVisitor`: the parsing of `Manifest<Meta>` is moved into `block_in_place` mode.
=> Run blocking fs operations & parsing in `block_in_place` mode

Cargo.toml
O3 mostly enables float optimization, more aggressive loop unrolling and
function inline.
O2 is probably OK, but I want to reduce the binary size a bit by using
opt level "s".
Edit:
The CI shows that the binary size sees a significant reduction for all targets, but does not have much impact on the performance of the binary.
It's likely that the bottleneck is the network and IO.
Also, if this is found to be a problem later, we can always [override the profile](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides) for the crates that matters, e.g. `zip`, `tar`, `bytes`.
=> Set `opt-level` for release to `s`

src/bins.rs, src/helpers.rs
This PR added a new function `helpers::atomic_install` and used it in `bins::BinFile::install_bin`.
`helpers::atomic_install` first attempts to use `rename` to atomically install the file.
When `rename` fails, it will switch to the fallback, which uses `tempfile::NamedTempFile` to create a named temporary file at the parent of `dst`, `std::io::copy` the `src` into the tempfile, then persist the named tempfile to `dst` atomically.
It also added a new function `helpers::atomic_symlink_file` and used it in `bins::BinFile::install_link`.
It creates a `tempfile::TempPath`, create a symlink with the `TempPath` as the linkname, then persist it to `link`.
=> feature: Install binaries atomically

src/errors.rs, src/helpers.rs, src/helpers/crate_name.rs, src/main.rs
=> Feature: Support specifing versions via `crate_name@req`

.github/workflows/build-and-integration-tests.yml
=> Speedup CI: Build cargo-binstall in debug mode for PR

Cargo.lock, Cargo.toml, ci-scripts/run_tests_unix.sh, src/helpers.rs, src/helpers/crate_name.rs, src/main.rs, src/metafiles/cvs.rs, src/target.rs
=> Feature: Implement batch installation

Cargo.toml
On M1 MacOS Darwin 21.5, this produces binary that is 0.3M smaller while
taking 10s less to build.
=> Use `opt-level = "z"` for release

src/binstall.rs, src/binstall/install.rs, src/main.rs, src/metafiles/v1.rs, src/metafiles/v2.rs
Update all metafiles once in `entry` to avoid race condition when updating them in parallel on different threads.
=> Fix race condition when updating metafile

src/main.rs
Put all binaries to a temporary directory under `dst` first, catching
some failure modes (e.g., out of space) before touching the existing
binaries. This directory will get cleaned up via RAII. 
Shamelessly copied from https://github.com/rust-lang/cargo/blob/caf3c37d90081a211a2457f8b5543ae4cddb0142/src/cargo/ops/cargo_install.rs#L384
=> Fix: Create `temp_dir` in `install_path`

.github/workflows/build-and-integration-tests.yml, .github/workflows/release-pr.yml, .github/workflows/release-tag.yml, Cargo.toml, build.rs, manifest.rc, release.toml, windows.manifest
This introduces the concept of a release PR:
- adds manual trigger on the Release PR github action
- it bumps the version numbers and does replacements via cargo-release
- it then pushes the result to a new branch and opens a PR with instructions to make a release
- merging the PR (with squash) triggers more github actions to:
1. create a tag on the repo
2. make a github release
The release PR also includes a space to add release notes, which are automatically extracted by the GHAs and used as the body of the published release.
The GHAs don't do an automated `cargo publish` for two reasons:
- those are irreversible; that's not so much a worry once established but until the GHAs work well it's preferable not to have any mistake require an extra bump and a yank
- the lack of scoped …
=> Releng improvements

.github/workflows/build-and-integration-tests.yml, .github/workflows/unit-tests.yml, Cargo.lock, Cargo.toml, Cross.toml, ci-scripts/install-deps.sh
Quite some time is spent compiling these images, so I create new features that allow system-wide libraries of these versions to be used.
However, I don't know how to install them inside the `cross` image, so they would still build these libraries and link with them statically.
This PR also disables building `zlib-ng` and uses native-tls on windows.
Edit:
This PR enables `zig-cc` for cross building.
=> Speedup ci by using liblzma-dev, libzip and libzstd provided by `apt`

.github/workflows/build-and-integration-tests.yml, Cross.toml
It has been a long time and the bugs on these targets might already be fixed by `cross`.
If not, then we can simply wait for release of 0.3.0, which adds support for `zig-cc` that can cross-compile any C/C++ code easily for any supported target.
=> Try to reenable armv7, aarch64 gnu targets

Cargo.lock, Cargo.toml, src/metafiles/v1.rs
The toml crate is unmaintained / not actively maintained, and may be replaced with toml_edit::easy anyway:
https://github.com/alexcrichton/toml-rs/issues/460#issuecomment-1163202480
Doesn't significantly affect overall build time:
```
$ hyperfine -p 'git s main; cargo clean' -p 'git s toml-edit; cargo clean' 'cargo build # toml' 'cargo build # toml-edit'
Benchmark 1: cargo build # toml
Time (mean ± σ):     34.329 s ±  3.220 s    [User: 225.791 s, System: 19.169 s]
Range (min … max):   32.100 s … 43.068 s    10 runs
Benchmark 2: cargo build # toml-edit
Time (mean ± σ):     34.315 s ±  1.331 s    [User: 225.706 s, System: 19.183 s]
Range (min … max):   32.607 s … 36.400 s    10 runs
Summary
'cargo build # toml-edit' ran
1.00 ± 0.10 times faster than 'cargo build # toml'
```
=> Replace toml with toml_edit

Cross.toml
As it is not actually supported yet by the cross version in CI, this is precautionary such that the build does not magically start failing. We can re-enable it later.
=> Disable zig for now

Cargo.toml, src/fetchers.rs, src/fetchers/gh_crate_meta.rs, src/fetchers/quickinstall.rs, src/formats.rs, src/helpers.rs, src/lib.rs
Solves #38 not by providing a custom extension for formats, but by trying all the standard extensions for the given format at once.
=> Find best download source out of alternatives (format extension)

.github/workflows/release-pr.yml
Minor cosmetic change, really. From this:
This is a release PR for version **0.11.0**.
**Use squash merge.** Upon merging, this will automatically build the CLI and create a GitHub release. You still need to manually publish the cargo crate.
```
$ cd 
$ cargo publish
```
---
To this:
This is a release PR for version **0.11.0**.
**Use squash merge.**
Upon merging, this will automatically build the CLI and create a GitHub release. You still need to manually publish the cargo crate.
```
$ git switch main
$ git pull
$ git checkout v0.11.0
$ cargo publish
```
=> Fix the instructions for publish on the release PR

.github/workflows/build.yml, Cargo.lock, Cargo.toml, ci-scripts/compile-settings.jq
- fancy-no-backtrace (enabled by default)
- fancy-with-backtrace (enabled on CI debug build)
- log_release_max_level_info
=> Add more features

Cargo.lock, Cargo.toml, src/bins.rs, src/binstall.rs, src/metafiles/v1.rs
- Use `Vec` instead of `BTreeSet` to store bins since it is already unique
- Use `CompactString` instead of `String` to store the name of bins since many of them are less than 24 bytes (`CompactString` can store up to 24 bytes inline on 64-bit platforms and 12 bytes on 32-bit platforms).
=> Optimze updating `CratesToml`

Cargo.lock, Cargo.toml, src/binstall.rs, src/binstall/install.rs, src/helpers.rs, src/helpers/flock.rs, src/main.rs, src/metafiles.rs, src/metafiles/binstall_v1.rs, src/metafiles/cvs.rs, src/metafiles/v1.rs
Implement https://github.com/ryankurte/cargo-binstall/issues/176#issuecomment-1193140151
=> Feature: Create metafile format for cargo-binstall

src/miniwasi.wast
As mentioned in #246, the imports must appear at the top; this wasn't checked by binaryen's tooling and doesn't change the output, but might as well have something strictly correct
=> Fix miniwasi.wast correctness

src/binstall/resolve.rs, src/errors.rs, src/helpers.rs, src/main.rs
- Add `-V` to print version (#248)
- Clean up some errors' documentation and names
- Allow `--manifest-path` to take both a crate folder path and a `Cargo.toml`'s path
- Rewrite some option help texts
- Add some help sections to organise things and be able to refer to overrides as a group
=> Add -V, clean up errors and help text

.github/workflows/build.yml, ci-scripts/compile-settings.jq
Support for #256: that way pure build args (e.g. `-Z` stuff) can be specified independently of the feature sets.
=> Split features and build args handling in build

src/binstall.rs, src/fetchers.rs, src/fetchers/gh_crate_meta.rs, src/fetchers/quickinstall.rs, src/main.rs
Use `CompactString` instead of `String` for strings that can be fit into 24b.
=> Minor fix (use `PathBuf` instead of `String` to relax utf-8 req) and micro optimization

Cargo.lock, Cargo.toml, src/binstall/resolve.rs, src/helpers/crate_name.rs, src/main.rs
Also contains some minor optimization by using `CompactString` in place of `String`.
=> Fix repeated crates on batch installation: Dedup them and only keep the last one

src/target.rs
Avoid spawning `ldd` if built with Glibc.
=> Optimize `target::linux::detect_target_linux`

src/binstall/install.rs
=> Fix passing `--quiet` to `cargo-install`

.github/workflows/build.yml, .github/workflows/unit-tests.yml
May speed up initial builds a bit
https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html
=> Enable sparse registry in CI

Cargo.lock, Cargo.toml, src/errors.rs, src/fetchers.rs, src/fetchers/gh_crate_meta.rs, src/helpers.rs, src/helpers/auto_abort_join_handle.rs, src/helpers/signal.rs, src/helpers/ui_thread.rs, src/main.rs
This PR added signal handling for:
- `ctrl_c`
- `SIGINT` (unix)
- `SIGHUP` (unix)
- `SIGTERM` (unix)
- `SIGQUIT` (unix)
It will abort the program and clean up the resource if received any of the signals listed above.
It also ignores `SIGUSR1` and `SIGUSR2` on unix.
This PR fixed #268 
=> Add Signal handling

README.md, SUPPORT.md
on the basis that most users will be using `binstall` rather than supporting it (and ideally we'll improve the support story too) i've simplified the main readme and split the support section out.
=> split docs, first step towards simplifying support instructions

ci-scripts/tests.sh, src/binstall.rs, src/binstall/install.rs, src/binstall/resolve.rs, src/drivers/crates_io.rs, src/drivers/version.rs, src/helpers.rs, src/helpers/crate_name.rs, src/helpers/version.rs, src/main.rs
=> Skip if already installed and add new cmdline option `--force`

README.md, ci-scripts/tests.sh, src/binstall/install.rs, src/binstall/resolve.rs, src/drivers/crates_io.rs, src/errors.rs, src/fetchers/gh_crate_meta.rs, src/fetchers/quickinstall.rs, src/main.rs
Resolves #291.
Also improves errors a bit, e.g.
```console
$ cargo binstall cargo-watch@9
16:00:25 [INFO] Installing package: 'cargo-watch@=9'
16:00:26 [ERROR] Fatal error:
× for crate cargo-watch
╰─▶ no version matching requirement '=9'
```
=> Don't prompt if there's nothing to do

SUPPORT.md, crates/bin/Cargo.toml, crates/lib/src/fetchers/gh_crate_meta.rs, crates/lib/src/fetchers/gh_crate_meta/hosting.rs, crates/lib/src/helpers/remote.rs, crates/lib/src/manifests/cargo_toml_binstall.rs, crates/lib/tests/parse-meta.rs
=> Support other git hosting services

.github/workflows/build.yml, Cargo.lock, crates/bin/Cargo.toml, crates/lib/Cargo.toml
=> Add new feature `trust-dns` to lib & bin

crates/lib/Cargo.toml, crates/lib/src/fetchers.rs, crates/lib/src/fetchers/gh_crate_meta.rs, crates/lib/src/ops/resolve.rs
Also [Optimize MultiFetcher: Impl with_capacity](https://github.com/cargo-bins/cargo-binstall/commit/032f9e12e6f7a526a5b04b007f540a688e28bd2f).
=> Optimize `GhCrateMeta::find`: use `FuturesUnordered`

crates/lib/src/drivers/crates_io/vfs.rs, crates/lib/src/drivers/crates_io/visitor.rs
=> Optimize `drivers::crates_io::Vfs`: Use `BTreeMap`

crates/lib/src/manifests/cargo_toml_binstall.rs
=> Use `BTreeMap` in field `PkgMeta::overrides`

SUPPORT.md, crates/lib/src/fetchers/gh_crate_meta.rs, crates/lib/src/fetchers/gh_crate_meta/hosting.rs, crates/lib/src/helpers/download/async_extracter.rs
Multiply paths with filenames to reduce duplication, and add variants of
whether there’s a v in front of versions or not.
Fixes #328
=> Explode out even more variants of default download URLs

Cargo.lock, crates/lib/Cargo.toml, crates/lib/src/drivers/crates_io.rs, crates/lib/src/fetchers/gh_crate_meta.rs, crates/lib/src/fetchers/quickinstall.rs, crates/lib/src/helpers/download.rs
I'm not entirely sure how to actually implement this, but that's a convenient API for it. Notably it's generic over the kind of digest, and defaults to a noop digest.
=> Add phantom digest support to download

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/entry.rs, crates/lib/Cargo.toml
by using function `AsyncClient::with_http_client` instead of
`AsyncClient::new`.
This gives us the following benefits:
- The connection pool of `reqwest::Client` is reused
- The configuration of `reqwest::Client` is also reused and obeyed in
`crates_io_api::AsyncClient` (https only, >=tls 1.2, user_agent,
etc).
=> Reuse reqwest client in `crates_io_api::AsyncClient`

.github/workflows/release-pr.yml
This is stuff I've learned/done over at watchexec:
- Enable commit signing with [gitsign](https://github.com/sigstore/gitsign)
- Use the short form of the checkout and do it first
- Default the version field to `patch` (less typing!)
=> Improve release-pr usage

.github/scripts/compile-settings.jq, crates/bin/Cargo.toml, crates/lib/Cargo.toml
but explicitly enable it in our own builds.
This is because using zlib-ng sometimes does not compile easily on Windows, and using the pure miniz_oxide offers a better install story from source.
For our binary builds, we can provide the optimal performance, and still do that for most users as they will update with cargo-binstall, getting our build as a second pass.
=> Disable zlib-ng for the default cargo-install build

Cargo.lock, crates/lib/Cargo.toml
=> Fix `tar` by temporarily using a fork

crates/binstalk/src/manifests/cargo_toml_binstall/package_formats.rs
Fixes: #377
Before;
```shell
❯ cargo run fnm --no-symlinks --pkg-url="https://github.com/Schniz/fnm/releases/download/v1.31.1/fnm-linux.zip" --pkg-fmt zip --bin-dir "{ bin }" --install-path /tmp/foo
Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Running `/home/user/playground/cargo-binstall/target/debug/cargo-binstall fnm --no-symlinks '--pkg-url=https://github.com/Schniz/fnm/releases/download/v1.31.1/fnm-linux.zip' --pkg-fmt zip --bin-dir '{ bin }' --install-path /tmp/foo`
error: Invalid value "zip" for '--pkg-fmt <PKG_FMT>': Matching variant not found
For more information try --help
```
After:
```shell
❯ cargo run fnm --no-symlinks --pkg-url="https://github.com/Schniz/fnm/releases/download/v1.31.1/fnm-linux.zip" --pkg-fmt zip --bin-dir "{ bin }" --install-path /tmp/foo …
```
=> fix: `pkg-fmt` parsing should be case insensitive

crates/bin/src/args.rs
Fixes #378
TODO:
- [] How to prevent those values be out of sync with https://github.com/cargo-bins/cargo-binstall/blob/757ecfaef8c56dcc4ef2aeee3687dea0847b3d1d/crates/binstalk/src/manifests/cargo_toml_binstall/package_formats.rs#L9
=> docs: add possible values to `pgk-fmt` argument

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/install_path.rs, crates/binstalk/src/helpers/statics.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/manifests/binstall_crates_v1.rs, crates/binstalk/src/manifests/cargo_crates_v1.rs
Fixed #388 
This PR:
- Add `--roots` cmdline option
- Use `env::var_os` to fetch env `CARGO_INSTALL_ROOTS`
- [Update manifest if `CARGO_INSTALL_ROOT` is specified](https://github.com/cargo-bins/cargo-binstall/commit/b8412d4a0efcbfeb350f229c1655b9abb72879d7)
- [Fix updating manifest: Use `cargo_roots` instead of default path](https://github.com/cargo-bins/cargo-binstall/commit/17b9f3b9354959a8df4794565c6d39f8c5960241)
- [Rm helpers::statics::cargo_home](https://github.com/cargo-bins/cargo-binstall/commit/33dd0b66bca4f2e1475175c206c6d15b0bbd320e) since it is no longer used
I've tested this PR locally by specifing `--roots /tmp/a` and installed crates `cargo-binstall` and `cargo-nextest` which are already installed in `$HOME/.cargo`.
`cargo-binstall` installs these two binaries to …
=> Support `--roots`

.github/scripts/compile-settings.jq, crates/bin/Cargo.toml, crates/bin/src/ui.rs
Also [Fix calculation of log_level in logging](https://github.com/cargo-bins/cargo-binstall/commit/1d4627c8637566f01030b1f9197b41008ab92a44) so that all enabling `log_release_max_level_*` in release build would also filter out all log messages except messages coming from `binstalk` and `cargo-binstall`.
=> Add new feature log_release_max_level_debug and enable it on CI release build

README.md
The crate _doesn't_ have the readme snapshot anymore, likely due to the new split crate layout; we should probably fix that but in the meantime this does the trick.
=> Use github source for latest version readme

Cargo.lock, crates/binstalk/Cargo.toml
So that downloading uncompressed binary can be faster for slow connection.
=> Enable feat gzip, brotli & deflate of dep reqwest

.github/scripts/tests.sh, crates/binstalk/src/bins.rs, crates/binstalk/src/ops/resolve.rs
so that crates like `sccache` and `git-cliff` would work as expected.
Fixed #357
This also fixed yet another bug in #417 where I forgot to join `data.bin_path` with the `bin_dir` before checking for its existence.
=> Make binaries with `required-features` optional

.github/scripts/tests.sh, .github/workflows/integration.yml, crates/binstalk/src/ops/install.rs, crates/detect-targets/src/detect.rs, crates/detect-targets/src/lib.rs
=> Use `CARGO` env variable if present

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/helpers/download.rs, crates/binstalk/src/helpers/remote.rs, crates/binstalk/src/ops/resolve.rs
* Disable tcp_nodelay for `reqwest::Client`
* Add new dep tower v0.4.13 with feature "limit" and "util" eabled
* Use `tower::limit::rate::RateLimit` for rate limiting
* Rm dep reqwest from crates/bin
* Add new arg `rate_limit` with default set to `5/1`
* Refactor `QuickInstall::report`: Use remote_exists instead of request
Fixed #457.
=> Disable `tcp_nodelay` for `reqwest::Client` and add rate limiting for https requests

.github/scripts/compile-settings.jq, .github/scripts/tests.sh, .github/workflows/build.yml, crates/bin/src/ui.rs
* Fix integration test: Make sure `cargo build cargo-binstall` would not fail due to binary already present
* Disable feature `zlib-ng` for release build
* Disable build-std for release build on aarch64-unknown-linux-gnu
* Fix clippy warning in unit test CI
* Fix compile-settings.jq
* Fix caching: Rm `restores-keys`
=> Fix unit test & integration CI and the release CI

crates/binstalk/src/ops/install.rs
If user interrupts `cargo-binstall` by signal while it is running `cargo-install`, then the `cargo-install` would continue to run at background even after `cargo-binstall` terminates.
Setting `cmd` to be kill_on_drop fixed this.
=> Fix `install_from_source`: Set `cmd` to be kill_on_drop

Cargo.lock, crates/binstalk/Cargo.toml, crates/binstalk/src/errors.rs, crates/binstalk/src/helpers/download/async_extracter.rs, crates/binstalk/src/helpers/download/stream_readable.rs, crates/binstalk/src/helpers/signal.rs, crates/binstalk/src/ops/resolve.rs
Extraction wasn't cancellable by `cancel_on_user_sig_term` used in `entry` since it calls `block_in_place`.
This PR adds cancellation support to it by adding a `static` variable `OnceCell` to `wait_on_cancellation_signal` so that once it returns `Ok(())`, all other calls to it after that point also returns `Ok(())` immediately.
`StreamReadable`, which is used in cancellation process, then stores a boxed future of `wait_on_cancellation_signal` and polled it in `BufReader::fill_buf`.
Note that for zip, the extraction process takes `File` instead of `StreamReadable` due to `io::Seek` requirement, so it cancelling during extraction for zip is still not possible.
This PR also optimized `extract_bin` and `extract_zip` by using `StreamReadable::copy` introduced to this PR instead of `io::copy`, …
=> Make extraction cancellable for `bin` and `tar` based formats

SUPPORT.md, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
This is the default format used by github action rust-build/rust-build.
=> Support default filename with underscores.

Cargo.lock, crates/bin/Cargo.toml
to convert all tracing spans and events to log
=> Add new dep tracing v0.1.37 with feat log-always in crates/bin

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/entry.rs, crates/bin/src/install_path.rs, crates/bin/src/main.rs, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/extracter.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/bins.rs, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/drivers/crates_io/visitor.rs, crates/binstalk/src/drivers/version.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/fs.rs, crates/binstalk/src/ops/install.rs, crates/binstalk/src/ops/resolve.rs, crates/binstalk/tests/parse-meta.rs
Resolved #522
* Add dep tracing v0.1.37 to binstalk
* Use `tracing` instead of `log` for logging in binstalk
* Rm dev dep `env_logger` since `log` is no longer used
* Rm unused dep `log` from binstalk
* Replace use of `log` with `tracing` in crates/bin
* Enable feat std of dep log in crates/bin
* Add dep tracing v0.1.37 to binstalk-downloader
* Replace use of `log` with `tracing` in binstalk-downloader
* Rm unused dep `log` from binstalk-downlaoder
* Wrap `ops::{install, resolve}` in `tracing::instrument`
* Wrap `Download::and_{extract, visit_tar}` in `instrument`
=> Replace use of `log` with `tracing`

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/bin_util.rs, crates/bin/src/logging.rs, crates/bin/src/main.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/errors.rs
* Enable feat ansi of dep tracing-subscriber
* Rm use of `tracing_appender::non_blocking`
since `cargo-binstall` is so simple that it doesn't need it.
* Use `tracing::{error, info}` in `MainExit::report`
* Use `tracing::{error, warn}` in `BinstallError::report`
* Add dep supports-color v1.3.1 to crates/bin
* Enable ansi of `tracing_subscriber::fmt` if stdout supports it
=> Enable coloring in console log

crates/binstalk-downloader/src/remote.rs, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/errors.rs
* Box `HttpError` in `binsalk_downloader::remote::Error::Http`
as `HttpError` contains `Url` which are too big.
* Box `HttpError` in `BinstallError::Http` same as the previous commit.
* Box `TinyTemplateError` in `BinstallError::Template`
since `TinyTemplateError` is 56 bytes large where most of the other variants are below 40 bytes large.
* Rm unsed variant `BinstallError::VersionUnavailable`
* Box `CratesIoApiError` in `BinstallError::CratesIoApi`
It is 32 bytes large while other variants are below 40 bytes large.
* Improve err msg for `BinstallError::CrateContext`
* Rm unused variant `BinstallError::VersionReq`
=> Optimization: Box variants in Error to reduce size and remove unused variants in `BinstallError`

crates/bin/src/entry.rs, crates/binstalk-downloader/src/download.rs, crates/binstalk-manifests/src/binstall_crates_v1.rs, crates/binstalk/src/bins.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/resolve.rs
* Optimize `Download::and_extract`: Avoid dup monomorphization
* Increase buffer size for binstall_crates_v1 to `4096 * 5`
* Optimize `opts::resolve`: Avoid unnecessary `clone`s
* Fix reserve in `opts::resolve`: Do not over-reserve
* Rename field `opts::Options::resolver` => `resolvers`
* Refactor: Extract new type `resolve::PackageInfo`
- which makes `opts::resolve_inner` easier to understand
- reduce number of parameters required for `download_extract_and_verify` and
`collect_bin_files`
- reducing size of future returned by `opts::resolve_inner` by dropping
`cargo_toml::{Manifest, Package}` as early as possible since
`Manifest` is 3000 Bytes large while `Package` is 600 Bytes large.
* Optimize `fetchers::Data`: Use `CompactString` for field name & version
since they are usually small …
=> Optimizations plus bug fix

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/install_path.rs, crates/bin/src/logging.rs, crates/bin/src/main.rs, crates/bin/src/ui.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk/src/drivers/version.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/helpers/jobserver_client.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/install.rs, crates/binstalk/src/ops/resolve.rs, crates/binstalk/src/ops/resolve/crate_name.rs
* Avoid potential panicking in `args::parse` by using `Vec::get` instead of indexing
* Refactor: Simplify `opts::{resolve, install}` API
Many parameters can be shared and put into `opts::Options` intead and
that would also avoid a few `Arc<Path>`.
* Optimize `get_install_path`: Avoid cloning `install_path`
* Optimize `LazyJobserverClient`: Un`Arc` & remove `Clone` impl
to avoid additional boxing
* Optimize `find_version`: Avoid cloning `semver::Version`
* Optimize `GhCrateMeta::launch_baseline_find_tasks`
return `impl Iterator<Item = impl Future<Output = ...>>`
instead of `impl Iterator<Item = AutoAbortJoinHandle<...>>`
to avoid unnecessary spawning.
Each task spawned has to be boxed and then polled by tokio runtime.
They might also be moved.
While they increase parallelism, spawning …
=> Minor refactor and optimization

Cargo.lock, crates/binstalk/Cargo.toml, crates/binstalk/src/bins.rs, crates/binstalk/src/drivers/crates_io/visitor.rs, crates/binstalk/src/drivers/version.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/install.rs, crates/binstalk/src/ops/resolve.rs
* Optimization: Rm `debug!` in `find_version`
printing all version iterated obviously doesn't help much in debugging
in the problem but rather just confusing.
Also this makes it hard for the compiler to optimize the iterators.
* Use let-else in `ManifestVisitor`
* Optimize `BinFile::preview_{bin, link}` for zero-copy
Return `impl Display` that lazily format instead of allocating a `String`
* Optimize `infer_bin_dir_template`: Generate dir lazily
* Optimize `find_version`: Lazily clone `version_req` only on err
* Refactor `find_version`: Use `bool::then_some`
* Add dep either v1.8.0 to binstalk
* Optimize `GhCrateMeta::find`: Avoid cloning and `Vec` creation
by using `Either`
* Optimize `ops::install::install_from_package`: Make it a regular fn
instead of async fn since it does not …
=> Minor optimization

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk/src/errors.rs
`cargo-binstall` should reject duplicate strategy in `--strategies` as it is illegal input and it cannot be interpreted reasonably.
* Reject duplicate strategy in `--strategies`
* Optimize `compute_resolvers`: Use `Vec::retain`
instead of `Iterator::filter` plus collecting into `Vec`.
* Optimize `compute_resolvers`: Reject `strategies.len() > Strategy::COUNT`
* Improve err msg for cases where user disabled all strategies
* Simplify `BinstallError::InvalidStrategies`: Takes `&'static str`
instead of `&'static &'static str` since other variants are larger than 8B.
=> Enforce strict strategies parsing rule: Reject duplicate strategy in `--strategies`

crates/binstalk/src/bins.rs, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/ops/resolve.rs
* Optimize `BinFile::preview_bin`: Use `Path::display` instead of `to_string_lossy` to avoid allocation.
* Refactor: Rm useless `AsRef::as_ref` call
* Optimize `GhCrateMeta::find`: Reduce fut size by converting `Url` to `String`
`Url` is much larger than `String`.
* Refactor `PackageInfo::resolve`: Destruct `Meta::binstall`
* Optimize `resolve::load_manifest_path`: Avoid allocation
=> More mionr optimizations

.github/workflows/release-pr.yml
Default rust in ubuntu-latest is too old.
=> Fix workflow release-pr: Install nightly toolchain

crates/binstalk/src/fetchers/gh_crate_meta.rs
So that the borrow checker know that `FuturesUnordered<F>` holds no reference to any data and thus it can further optimize future returned by `GhCrateMeta::find`.
=> Return `Future + 'static` in `GhCrateMeta::launch_baseline_find_tasks`

crates/binstalk-downloader/src/download/stream_readable.rs, crates/binstalk/src/helpers/signal.rs
as there is no need to randomize the first one to be polled.
For `cancel_on_user_sig_term` and `StreamReadable::fill_buf`, the cancellation future should always to be polled first so that user would feel responsive.
=> Optimize use of `tokio::select!`: Use biased selection

crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/ops/resolve.rs
* Optimize `Fetcher::find`: Make it non-async to avoid boxing
and return `AutoAbortJoinHandle<...>` instead.
Since spawning a new task in tokio box the future anyway, boxing the
returned future again in `Fetcher::find` merely adds unnecessary
overheads.
* Optimize `QuickInstall::report`: Make it async fn instead of ret `JoinHandle`
This provides several benefits:
- On debug build, no task will be spawned
- The calls to `self.stats_url()` can be evaluated in parallel.
- The task now returns `()` so that the task spawned is smaller.
* Fix `QuickInstall::find`: `warn!` if quickinstall report fails
=> Optimize `Fetcher::find` and fix quickinstall reporting

crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/errors.rs, crates/binstalk/src/ops/install.rs, crates/binstalk/src/ops/resolve.rs
* Optimize `BinstallError::CratesIoApi`: Extract new type `errors::CratesIoApiError` and box it
Also improve `<CratesIoApiError as Display>::fmt` impl.
* Optimize `BinstallError::SubProcess`: Use `Box<str>` instead of `String`
* Optimize `BinstallError::CargoManifest`: Box `CargoTomlError`
* Optimize `BinstallError::VersionParse`: Extract `VersionParseError` and box it
Also improve `<VersionParseError as Display>::fmt` impl.
* Optimize `BinstallError::CrateContext`: Extract `CrateContextError` and box it in
* Optimize `install_from_source`: Only format `cmd` on err
=> Optimize `BinstallError`: Reduce size from 40B to 32B

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/main.rs, crates/binstalk/src/errors.rs
* Fix reporting parsing error from `args::parse`
Report it in `args::parse` by using `Args::command().error(...).exit()`
instead of returning `BinstallError`.
* Rm unused variant `BinstallError::OverrideOptionUsedWithMultiInstall`
* Refactor: Move `strategies` validation into `args::parse`
* Rm unused variant `BinstallError::InvalidStrategies`
* Add new unit test `args::test::verify_cli`
=> Fix error reporting in main and move all arg validation into fn `args::parse`

.github/scripts/tests.sh, crates/bin/src/entry.rs, crates/binstalk-manifests/src/cargo_crates_v1.rs, crates/binstalk-manifests/src/lib.rs
* Add & Impl new fn `CratesToml::collect_into_crates_versions`
to iterate over crates listed in cargo_crates_v1, accessing their names
and versions.
* Re-export `CompactString`, `Version` & `Url` in binstalk-manifests
for convenience
* Fix `CratesToml::load_from_path`: Wrap `File` in `FileLock::new_shared`
to avoid concurrent write while reading the file.
* Filter out installed crates in cargo_install_v1_metadata
* Make match in `filter_out_installed_crates` more explicit
* Add new test `cargo_crates_v1::test::test_loading`
* Optimize `CratesToml`: Use `Vec` instead of `BTreeMap`
since we cannot simply call `BTreeMap::get` to find an entry for a crate
anyway.
This also accidentally fixed the CI.
* Impl new API `CratesToml::remove`
* Fix`CratesToml::append_to_path` by removing previous …
=> Feature: Check for installed crates in cargo_install_v1_manifest

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/async_tar_visitor.rs, crates/binstalk/src/drivers/crates_io/visitor.rs
* Add new dep tokio-tar v0.3.0 to binstalk-downloader
* Add new dep tokio-util v0.7.4 with feat io to binstalk-downloader
* Add dep async-trait v0.1.59 to binstalk-downloader
* Add new dep async-compression v0.3.15 to binstalk-downloader
with features "gzip", "zstd", "xz", "bzip2", "tokio".
* Rewrite `Download::and_visit_tar` to use `tokio-tar`
to avoid the cumbersome `block_in_place`.
* Apply temporary workaround: Rm use of let-else in mod visitor
=> Optimization: Rewrite Download::and_visit_tar to use tokio-tar

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/extracter.rs, crates/binstalk-downloader/src/download/stream_readable.rs, crates/binstalk-downloader/src/download/utils.rs, crates/binstalk-downloader/src/download/zip_extraction.rs
* Add new dep async_zip v0.0.9 to binstalk-downloader
with features "gzip", "zstd", "xz", "bzip2", "tokio".
* Refactor: Simplify `async_extracter::extract_*` API
* Refactor: Create newtype wrapper of `ZipError`
so that the zip can be upgraded without affecting API of this crate.
* Enable feature fs of dep tokio in binstalk-downloader
* Rewrite `extract_zip` to use `async_zip::read::stream::ZipFileReader`
which avoids writing the zip file to a temporary file and then read it
back into memory.
* Refactor: Impl new fn `await_on_option` and use it
* Optimize `tokio::select!`: Make them biased and check for cancellation first
to make cancellation takes effect ASAP.
* Rm unused dep zip from binstalk-downloader
=> Optimize `extract_zip`: Use `async_zip::read::stream::ZipFileReader` to avoid temporary file

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/async_tar_visitor.rs, crates/binstalk-downloader/src/download/stream_readable.rs, crates/binstalk-downloader/src/download/utils.rs, crates/binstalk-downloader/src/download/zip_extraction.rs, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/helpers/signal.rs, crates/binstalk/src/ops/resolve.rs
- Refactor: Mv fn `utils::asyncify` into mod `utils`
- Improve err msg for task failure in `utils::asyncify`
- Make sure `asyncify` always returns the same annoymous type
that implements `Future` if the `T` is same.
- Rewrite `extract_bin` to avoid `block_in_place`
support cancellation by dropping
- Rm unused dep scopeguard from binstalk-downloader
- Rewrite `extract_tar_based_stream` so that it is cancellable by dropping
- Unbox `extract_future` in `async_extracter::extract_zip`
- Refactor `Download` API: Remove `CancellationFuture` as param
since all futures returned by `Download::and_*` does not call
`block_in_place`, so they can be cancelled by drop instead of using this
cumbersome hack.
- Fix exports from mod `async_tar_visitor`
- Make `signal::{ignore_signals, …
=> Refactor `binstalk-downloader` APIs: Remove `cancellation_future` plus optimizations

crates/binstalk-downloader/src/download.rs
=> Fix `binstalk-downloader`: Re-export `TarBasedFmt`

crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/helpers/signal.rs
Since the other await point in `GhCrateMeta::find` only needs `Arc<Self>` and `handles` to be saved, which is much smaller than the future returned by `Remote::get_redirected_final_url`
=> Optimization: Box fut `Remote::get_redirected_final_url` in `GhCrateMeta::find`

.github/workflows/build.yml
In a dockerfile I have `rust_target=$(rustc -vV | awk '/^host:/{ print $2 }') && curl https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-$rust_target.tgz`; it broke with the most recent release because the `rust:1.65` image has glibc 2.31 and the 0.18.0 release built on ubuntu-22.04 ([build log](https://github.com/cargo-bins/cargo-binstall/actions/runs/3676457750/jobs/6217128087)), which has a more recent version (2.35?). This commit pins it to 20.04, so the glibc version required by the release binaries remains lower. (If possible, a 0.18.1 release to fix this would be really nice, or otherwise I can use a workaround for now)
=> Build -gnu targets on ubuntu-20.04

Cargo.lock, crates/binstalk-manifests/Cargo.toml, crates/binstalk-manifests/src/cargo_crates_v1.rs, crates/binstalk-manifests/src/cargo_crates_v1/crate_version_source.rs, crates/binstalk-types/Cargo.toml, crates/binstalk-types/src/crate_info.rs, crates/binstalk-types/src/lib.rs
* Add new dep maybe-owned v0.3.4 to binstalk-types with features serde
* Re-export maybe_owned in binstalk-types
* Optimize `CrateSource::url`: Use `MaybeOwned<'static, Url>`
to avoid cloning in `CrateSource::cratesio_registry`
* Optimize `Source`: Use `MaybeOwned<'static, Url>`
to avoid cloning in `Source::cratesio_registry` and
`impl From<&CrateSource> for Source`.
* Optimize `Source`: Add lifetime `<'a>` to avoid cloning
in `impl<'a> From<&'a CrateSource> for Source<'a>`
* Optimize `CratesToml::append_to_path`: Avoid cloning
caused by `CrateVersionSource::from` by manually `format!` name, version
and source into string.
* Add new dep beef v0.5.2 to binstalk-manifests with features impl_serde
* Optimize `CratesToml::append_to_path`: Eliminate `metadata.bins.clone()` by using `Cow`
* …
=> Optimize binstalk-{manifest, types}

crates/bin/src/entry.rs
Honor `.crates.toml` only since `cargo-uninstall` can only update `.crates.toml`, not binstall's own manifest.
Fixed #625
=> Fix reinstalling crates after removed by `cargo-uninstall`

crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_tar_visitor.rs, crates/binstalk/src/drivers/crates_io.rs, crates/binstalk/src/drivers/crates_io/visitor.rs
by removing method `TarEntriesVisitor::finish` and associated type `TarEntriesVisitor::Target`.
=> Optimize `Download::and_visit_tar`: Use trait object to avoid monomorphization

crates/binstalk-manifests/src/cargo_crates_v1.rs, crates/binstalk-manifests/src/helpers.rs
* Optimize `CratesToml::load_from_reader`: Avoid dup monomorphization
* Optimize `CratesToml::write_to_writer`: Avoid dup monomophization
* Optimize `create_if_not_exist`: Take `&path` to avoid dup monomorphization
* Fix `CratesToml::write_to_path`: Use exclusive file lock
to prevent race conditions.
=> Minor Optimization and fix for `bintalk-manifests`

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/entry.rs, crates/bin/src/lib.rs, crates/bin/src/manifests.rs
Fixed #588
* Add new dep fs-lock v0.1.0 to crates/bin
* Refactor: Impl new type `Manifests` in crates/bin
for managing manifests.
* Fix #588 race cond updating `.crates.toml`
=> Fix #588 race cond updating `.crates.toml`

crates/detect-targets/Cargo.toml, crates/detect-targets/src/detect.rs, crates/detect-targets/src/detect/linux.rs
- Enable `guess_host_triple` on all targets
- Fix `detect_targets_linux`: Detect runtime arch/libc using `guess_host_triple` instead of using the one specified in `TARGET`.
- Add support for android in `detect_targets`
=> Fix `detect_targets_linux`: Detect arch/libc at runtime using `guess_host_triple`

.github/scripts/release-pr-template.ejs
We do nothing with it yet but eventually that will let us move away from parsing commit messages for releases.
=> Add release metadata in PR (from release-pr v2)

.github/workflows/ci.yml
Little trick from the watchexec repo: instead of closing/opening the release PRs, this makes it such that enabling auto-merge triggers CI
=> Run CI on auto-merge enable

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/zip_extraction.rs
Reverts cargo-bins/cargo-binstall#709
Unless async_zip does a 0.0.11 release before we merge this, let's get the breakage out
=> Revert "Bump async_zip from 0.0.9 to 0.0.10"

.github/workflows/ci.yml
Support says the behaviour we observed [is intentional](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#example-not-requiring-successful-dependent-jobs) and this is how to fix it.
=> Fix "Tests pass" step

Cargo.lock, crates/binstalk-manifests/Cargo.toml, crates/binstalk-manifests/src/cargo_crates_v1.rs
Since now toml simply uses toml_edit, there is no reason to continue using it as it merely increase compilation time and bloat.
Instead, we switch to toml_edit v0.18.0 with feature serde enabled.
This also remove the `CratesTomlParseError::TomlParseNonUtf8` variant intorduced in #736.
=> Switch from toml back to toml_edit

crates/bin/src/logging.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
* Refactor `logging`: Extract `report_err`
* Optimize `get_default_pkg_url_template`: Return iter instead of `Vec`
to avoid heap allocation.
* Refactor `GhCrateMeta::find`: Rm `launch_baseline_find_tasks`
* Optimize `GhCrateMeta::find`: Avoid cloning `Cow<'_, str>`
* Improve `report_err` output: Print newline after msg
=> Minor optimization for bin and binstalk

crates/binstalk-types/src/cargo_toml_binstall/package_formats.rs, crates/binstalk/src/errors.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs
but `pkg-url` also does not contain format, archive-format or
archive-suffix which is required for automatically deducing the pkg-fmt.
In these cases, we would call `PkgFmt::guess_pkg_format` to try out best
to figure out the pkg-fmt, otherwise we just return an error.
* Fix fmt of mod `<GhCrateMeta as Fetcher>::find`
* Add new variant `BinstallError::InvalidPkgFmt`
* Impl new fn `PkgFmt::guess_pkg_format`
* Improve `GhCrateMeta`: Detect cases where `pkg-fmt` is not specified
but `pkg-url` also does not contain format, archive-format or
archive-suffix which is required for automatically deducing the pkg-fmt.
In these cases, we would call `PkgFmt::guess_pkg_format` to try out best
to figure out the pkg-fmt, otherwise we just return an error. …
=> Improve `GhCrateMeta`: Detect cases where pkg-fmt is not specified

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/delay_request.rs
Fixed #747
- Add dep compact_str v0.6.1 to binstalk-downloader
- Impl new type `DelayRequest`
- Handle 503/429 with wait duration > `MAX_RETRY_DURATION` by simply taking the min
- Fix `Client::send_request_inner`: Ensure 503/429 get propagated to other requests
even if the current requests reach its maximum retry and decides to
simply return an error.
=> Fix "Too many "Too Many Requests" log"

crates/binstalk/src/bins.rs, crates/binstalk/src/fs.rs, crates/binstalk/src/helpers/signal.rs
Fixes #728
This isn't as good as using reflinks but let's fix the immediate bug for now.
=> Fix #728: fallback to copy when symlinking on windows

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/async_tar_visitor.rs, crates/binstalk-downloader/src/download/zip_extraction.rs, crates/binstalk-downloader/src/remote.rs
`futures-util` has too many dependencies and it contains a lot of code of which we only use a tiny bit of them.
=> Replace dep `futures-util` with `futures-lite` in binstalk-downloader

Cargo.lock, crates/binstalk/Cargo.toml, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/helpers/futures_resolver.rs
futures-util has too many dependencies and it contains a lot of code of which we only use `futures_util::stream::{FuturesUnordered, StreamExt}`.
We don't even need most of the functionalities in `FuturesUnordered` as we just need the output of first future that either returns `Err(_)` or `Ok(Some(_))`.
So we replace it with ou own homebrew solution (~80 loc) and it's easier to use.
=> Replace dep futures-util with `helpers::FuturesResolver`

crates/bin/Cargo.toml, crates/binstalk/Cargo.toml
Default features were turned on for binstalk and the `static` and `pkg-config` features of cargo-binstall didn't do anything
=> Make disabling static and rustls features possible

.github/workflows/ci.yml, crates/bin/src/logging.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/delay_request.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs
Fixed #779 #791 
- Retry request on timeout
- Retry for `StatusCode::{REQUEST_TIMEOUT, GATEWAY_TIMEOUT}`
- Add `DEFAULT_RETRY_DURATION_FOR_RATE_LIMIT` for 503/429
if 503/429 does not give us a header or give us an invalid header on
when to retry, we would default to
`DEFAULT_RETRY_DURATION_FOR_RATE_LIMIT`.
- Fix `Client::get_redirected_final_url`: Retry using `GET` on status code 400..405 + 410
- Rename remote_exists => remote_gettable & support fallback to GET
if HEAD fails due to status code 400..405 + 410.
- Improve `Client::get_stream`: Include url & method in the err of the stream returned
=> Feature: Better retry policy in `binstalk-downloader`

SUPPORT.md, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs
which does not contain `target`, hence it might report the binary being available for any target we specified.
=> Rm `NOVERSION_FILENAMES` "{ name }{ archive-suffix }"

crates/binstalk-downloader/src/download/async_extracter.rs
which would cause the `StreamReadable` to return eof even if the underlying stream is still open and has not sent EOF yet.
Fixed #777
=> Fix use of `StreamReadable`: Ensure no empty `Bytes`

crates/binstalk/src/bins.rs, e2e-tests/uninstall.sh, justfile
`bins::BinFile::new` does not include `binary_ext` in the `BinFile::base_name`.
Also add regression e2e-test.
Fixed #801
=> Fix bin names in `.crates.toml` on win

justfile
Enable feature `pkg-config` and `log_release_max_level_debug` for debug build and enable feature `static`, `trust-dns` and `log_release_max_level_debug` for release build.
=> Adjust feature flags enabled on CI

.github/workflows/release-build.yml, justfile
- Build `x86_64-unknown-linux-gnu` using `cargo-zigbuild`
- Build all `*-gnu` targets on glibc 2.17 for backwards compatibility
- Use ubuntu-latest image everywhere
=> Improve CI: All in cargo-zigbuild for linux targets

crates/bin/Cargo.toml, crates/binstalk-downloader/Cargo.toml, crates/binstalk/Cargo.toml, justfile
Fixed #806
- Add new feature flag `cross-lang-fat-lto` and enable it on release for linux
- Enable `-C linker-plugin-lto` for linux
- Only use `-Z gcc-ld=lld` on non-windows targets when `cargo-zigbuild` is not enabled
=> Enable cross-lang-fat-lto on Linux

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/certificate.rs
for specifying root ceritificates used for https connnections.
And remove old environment variable `CARGO_HTTP_CAINFO`, `SSL_CERT_FILE`
and `SSL_CERT_PATH` to avoid accidentally setting them, especially in CI
env.
Also:
- Rm fn `binstalk_downloader::Certificate::from_env`
- Enable feature `env` of dep `clap` in `crates/bin`
- Add new dep `file-format` v0.14.0 to `crates/bin`
- Use `file-format` to determine pem/der file format when loading root certs
- Rm fn `binstalk_downloader::Certificate::open` and enum `binstalk_downloader::OpenCertificateError`
=> Add opt `--root-ceritificates` & env `BINSTALL_HTTPS_ROOT_CERTS`

.github/workflows/release-build.yml, justfile
Plus printing `RUSTFLAGS` for justfile target build & check
=> Run e2e test for release build and fix it by switching back to stable

justfile
Without `-Zgcc-ld=lld` using `--icf=safe` will fail on MacOS.
=> Disable `--icf=safe` on MacOS

.github/actions/just-setup/action.yml, .github/workflows/ci.yml, .github/workflows/release-build.yml, justfile
- Remove `tools: cross` input to `actions/just-setup`
since we use `cargo-zigbuild` for cross compiling instead of `cross-rs`
now.
- Only install `cargo-zigbuild` in `just ci-install-deps` if `JUST_USE_CARGO_ZIGBUILD` is enabled
- Include hash of `rustc -vV` in `build-cache`
Switching between different versions of `rustc` will cause all crates to be
rebuilt using new `rustc`.
- Replace input `cache` with `index-cache` and `build-cache` in `actions/just-setup`
for better control of caching behavior
-  Reuse workflow `test`'s `build-cache` in workflow `lint`
=> Speedup CI

crates/binstalk-downloader/src/remote.rs
Fixed #835
Using `HEAD` for this would often cause false negative that requires the `Client` to fallback to `GET`, which creates a lot of requests even if the url doesn't exist and then get cargo-binstall rate limited by GitHub/GitLab/etc.
=> Only use `GET` in `remote::Client::remote_gettable`

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs
- Add option `--no-discover-github-token` for disabling this behavior
- Add new dep gh-token v0.1.0 to crates/bin
- Extract github-token from git-credentials or gh config if `--github-token` or
environment variable `GITHUB_TOKEN` is not present.
=> Extract GitHub token from file if `--github-token` or env variable `GITHUB_TOKEN` is not present

crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/extracted_files.rs, crates/binstalk-downloader/src/download/zip_extraction.rs, crates/binstalk/src/bins.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/ops/resolve.rs, justfile
to avoid collecting extracted files from disk again in resolution stage.
=> Return a list of files written to disk in `binstalk_downloader::download::Download::and_extract`

crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/extracted_files.rs, crates/binstalk-downloader/src/download/zip_extraction.rs, crates/binstalk/src/bins.rs
- Fix zip extraction code: Ensure dir is rwx and file is readable for curr user
- Add more integration test for `ExtractedFiles`
- Fix `bins::infer_bin_dir_template` introduced in #856
=> Fix zip extraction and `bins::infer_bin_dir_template`

crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/helpers/remote.rs, e2e-tests/upgrade.sh
- Refactor: Extract new fn `binstalk::helpers::remote::does_url_exist`
- Use new quickinstall release schema in `binstalk::fetchers::QuickInstall`
- Optimize `fetchers::QuickInstall`: Generate url once in `Fetcher::new`
Avoid repeated string allocation plus `Url` parsing.
This also makes changing package_url and stats_url easier.
- Optimize `QuickInstall::report`: Use HEAD instead of GET
=> Use Quickinstall new release schema

justfile
while we cannot enable cross-lang-fat-lto on MacOS due to linker error described [here], it turns out that enabling the feature `cross-lang-fat-lto` does not break the build.
[here]: https://github.com/cargo-bins/cargo-binstall/issues/806#issuecomment-1454989522
=> Enable only feature `cross-lang-fat-lto` on MacOS

crates/detect-targets/src/detect.rs, crates/detect-targets/src/detect/macos.rs
Fixed #857
Run `arch -arch x86_64 /usr/bin/true` to check whether rosetta2 is enabled and working.
=> Fix x86_64 fallback for aarch64 MacOS

README.md
The link was dead and the entry was probably removed / moved over to SUPPORT.md?
I changed the wording as its meant for end uses which don't care about Cargo.toml.
Also the example is a bit easier to read with each argument in their own line.
=> docs(readme): fix link to metadata

.github/workflows/release-build.yml, justfile
to make the pre-built artifacts auditable by `cargo-audit` and other tools.
=> Use `cargo-auditable` for release build

crates/bin/src/bin_util.rs, crates/bin/src/entry.rs, crates/bin/src/main.rs
The startup/init code in `entry::install_crates` performs a lot of blocking operations, from testing if dir exists to reading from files and there is no `.await` in there until after the startup.
There are also a few cases where `block_in_place` should be called (e.g. loading manifests, loading TLS certificates) but is missing.
Most of the `Args` passed to `entry::install_crates` are actually consumed before the first `.await` point, so performing startup/init code eagerly would make the generated future much smaller, reduce codegen and also makes it easier to optimize.
=> Perform startup/init code eagerly in `entry::install_crates`

e2e-tests/live.sh, e2e-tests/self-upgrade-no-symlink.sh, e2e-tests/strategies.sh, e2e-tests/tls.sh, e2e-tests/uninstall.sh
This will avoid tests takes half an hour on release because the artifacts aren't there yet, and also free us from spurious failures due to other projects making releases.
=> Use known-working versions for tests

.github/actions/just-setup/action.yml, Cargo.toml
Fixed #911
sccache cannot cache build artifacts if incremental mode is enabled.
=> Use sccache for build cache and disable incremental mode in CI

crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/ops/resolve.rs
Fixed https://github.com/cargo-bins/cargo-quickinstall/issues/195
- Fix `fetchers::QuickInstall`: Stop sending stats for `universal-apple-darwin`
since quickinstall only supports targets officially supports by rust.
- Only send stats report to quickinstall if the `Fetcher::find` is `.await`ed on
This prevents stats report to be sent for cases where the `QuickInstall` fetcher
is actually unused, e.g. resolved to `GhCrateMeta` or other `QuickInstall` fetcher
with different target.
This also reduces amount of http requests created in background.
=> Fix `fetcher::QuickInstall`stats report sending

crates/binstalk/src/fetchers/quickinstall.rs
This bug was reintroduced by #919 and it was fixed by #918
=> Fix `QuickInstall` report bug for target `universal2-apple-darwin`

crates/leon/src/parser.rs
Replace the algorithm with explicit state and complex matching with a loop that encodes state in the current structure of the loop.
The new code is much more readable and might be more performant since it uses `str::find`/`str::split_once` to look for next token instead of manually iterating over `str::chars`.
=> Rewrite `Template::parse_items`: More readable & better perf

crates/bin/src/args.rs
Partially resolve #731
Using symlinks not only add unnecessary bloat to users' `$CARGO_HOME/bin` directory, but it actually breaks `sccache`, which inspects its binary name and decides how to act on.
For `sccache` to function, it must be invoked directly or use a hard link.
=> Enable `--no-symlinks` by default and fix `sccache` installation

.github/workflows/cache-cleanup.yml, cleanup-cache.sh
since cache-cleanup will issue a lot of gh api requests, running the workflow right after the PRs would cause the GH API to rate limit all workflows (including our CI for testing and release) that they can no longer upload artifacts and `cargo-binstall` would have to fallback to sending GET requests instead of using GH API, which makes it a lot slower and more likely to fail.
This PR changes it to be run at 3am and 4:30am which nobody would submit any PR at that time and then remove all caches of the top 20 closed prs.
The workflow can also now be triggered manually just in case there are too many caches.
=> Run cache-cleanup at 3am & 4:30am AEST instead of after every PR

.github/actions/just-setup/action.yml, .github/workflows/ci.yml, .github/workflows/release-build.yml
Remove `mozilla-actions/sccache-action@v0.0.2` and instead use `taiki-ie/install-action` to install `sccache`, since we already use `taiki-e/install-action` for installing crates.
This PR also refactor just-setup.yml and use pass `GITHUB_TOKEN` to `taiki-e/install-action` which uses `cargo-binstall` for installing `cargo-auditable` and `sccache`.
=> Upgrade CI to use sccache v0.4.0 for caching

.github/workflows/release-build.yml
Since release build enables a lot of optimization, disable debug assert and possibly change the code to be run, it's better to run the tests again.
=> Run unit tests in `release-build.yml`

.github/workflows/ci.yml
Since we already run test on x86_64-unknown-linux-musl in `release-build.yml` and x86_64-unknown-linux-musl is almost identical to x86_64-unknown-linux-gnu except for the libc, there's no need to run the tests in `ci.yml`.
=> Speedup `ci.yml`: Do not run tests on x86_64-unknown-linux-musl

.github/workflows/ci.yml, justfile
We just want to make sure cargo-binstall can compile for the target, we don't want to pull in the extra dependencies.
=> Avoid checking dev-deps for jobs `*-check` and `lint` in workflow `ci.yml`

README.md
The Armv7 download link was pointing at the x86 release
=> Fix download link for armv7 release in readme (#980

.github/workflows/ci.yml
Since it is run on PR anyway, we should also run it on main just in case it fails, i.e. merging of PRs without rebasing against main to test out latest changes.
It will now also be run on draft PR so that they can test out the changes and find out bugs before making it ready to review.
This change will also increase cache hits on PR, thus speeding up the CI.
=> Run `release-build.yml` unconditionally for consistency & inc cache hits

.github/dependabot.yml, .github/workflows/release-pr.yml, Cargo.lock, Cargo.toml, crates/bin/src/args.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs, crates/binstalk/src/helpers/futures_resolver.rs, crates/leon-macros/Cargo.toml, crates/leon-macros/LICENSE-APACHE, crates/leon-macros/LICENSE-MIT, crates/leon-macros/src/lib.rs, crates/leon-macros/tests/parsing.rs, crates/leon/Cargo.toml, crates/leon/src/error.rs, crates/leon/src/lib.rs, crates/leon/src/macros.rs, crates/leon/src/template.rs
`leon_macros::template!` can parse template at compile-time.
It accepts a utf-8 string literal and uses `leon` internally to parse it, then generate code that evaluates to `Template<'static>`.
- Exclude fuzz from crate leon when publishing
- Impl fn-like proc-macro `leon_macros::template!`
- Add dep `leon-macros` to binstalk
- Use `leon_macros::template!` in `binstalk::fetchers::gh_crate_meta::hosting`
- Add doc for `leon-macros` in `leon`
=> Add new crate `leon-macros` that provide `template!` with identical syntax as runtime parsing

.github/workflows/ci.yml, crates/binstalk-downloader/src/gh_api_client.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/gh_crate_meta/hosting.rs, e2e-tests/live.sh, e2e-tests/manifest-path.sh, e2e-tests/other-repos.sh, e2e-tests/self-upgrade-no-symlink.sh, e2e-tests/strategies.sh, e2e-tests/subcrate.sh, e2e-tests/tls.sh, e2e-tests/uninstall.sh, e2e-tests/upgrade.sh, e2e-tests/version-syntax.sh, justfile
Fixed #838
- Add new key `subcrate` for rendering `pkg-url`
- Add new release paths in GitHub, GitLab & SourceForge using key `subcrate` for auto-detection
- Add subcrate detection for GitHub and GitLab
- Add `debug!` when using gh api token in `GhApiClient::new`
- Add subcrate testing to `e2e-tests/subcrate.sh`
- Bump cargo-release to 0.24.9 in e2e-tests/live.sh
to fix test failure on MacOS without libssl installed in `/usr/local/`.
- Optimize GhCrateMeta: Detect subcrate and repo-host in `Data::get_repo_info`
to cache the result and avoid duplicate works, this also makes the code
more ergonomic by removing the need to some `unwrap()` plus making it
more efficient since we don't need to clone the url just to modify it.
- Add instrument to `Data::get_repo_info`
- Fix `shellcheck` err in …
=> Support subcrate in repo

.github/workflows/release-build.yml, justfile
`cargo-test` cannot share its artifacts with `cargo-build` and vice
versa, plus running `e2e-tests` in release build is enough to find out
potential miscompilation.
=> Speedup `release-build.yml`: Do not run `unit-tests`

crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/LICENSE-APACHE, crates/binstalk-downloader/LICENSE-MIT
This PR switches license of binstalk-downloader from GPL 3.0 to "Apache-2.0 OR MIT", which requires consent from all contributors who modified the corresponding code, including:
=> Switch binstalk-downloader license to "Apache-2.0 OR MIT"

crates/binstalk/src/drivers/crates_io.rs
If `version_req` requests a specific version instead of a range, then there is no need to pull all versions available from https://crates.io/api/v1/crates
=> Optimize `fetch_crate_cratesio` for exact version

.github/workflows/ci.yml, .github/workflows/release-build.yml
LTO takes way too long and it is mature enough that it usually does not have any miscompilation.
=> ci: Disable lto for `ci.yml` job release-builds

.github/actions/just-setup/action.yml, .github/workflows/ci.yml, .github/workflows/release-build.yml, justfile
Fixed #1038
sccache is not very effective at caching dependencies, the external C/C++ is recompiled in every ci and it takes a lot of time.
Compilation of other Rust dependencies also takes quite some time and sccache is not helping at all, so I decided to switch to `Swatinem/rust-cache@v2`.
The downside of the new caching method is that a new cache conntaining part of the `.cargo/` and `target/` will be created whenver `Cargo.lock`/`Cargo.toml` changes, but it can still reuse the old cache to create new caching.
This is acceptable given that `sccache` often fails to reuse cache due to rate limiting from GHA, since it is not designed for use like a s3 object pool, and `sccache` will create a lot of new cache artifacts for a given branch that cannot be reused in main and would have to …
=> ci: Switch to `Swatinem/rust-cache@v2`

README.md, install-from-binstall-release.ps1
I saw the one-liner added for Unix systems (in #1073 / #1074) and thought it should be possible for Windows :)
The script should have the same behaviour as the Bash version, and the oneliner temporarily (scoped to the current terminal session) disables Powershell's Execution Policy.
The url used in the script is for after the PR is merged, use the following if you want to test:
```
Set-ExecutionPolicy Unrestricted -Scope Process && iex (iwr "https://raw.githubusercontent.com/supleed2/cargo-binstall/main/install-from-binstall-release.ps1").Content
```
=> Add one-liner for installing `cargo-binstall` on Windows

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk/src/bins.rs, crates/binstalk/src/fs.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/resolve/resolution.rs, e2e-tests/no-track.sh, justfile
Same as `cargo-install`'s `--no-track`.
It is also passed to `cargo-install` if it is invoked.
Also fixed `fs::atomic_symlink_file` which on Windows could fallback to
non-atomic install if symlinking failed.
=> feat: Add new cmdline option `--no-track`

Cargo.lock
- base64 v0.21.0 -> v0.21.2, rollback msrv to 1.57
- clap v4.3.0 -> v4.3.1, (derive) Reduce the amount of generated code
- clap_builder v4.3.0 -> v4.3.1
- clap_derive v4.3.0 -> v4.3.1
=> dep: Update base64 and clap

Cargo.lock, crates/detect-targets/Cargo.toml, crates/detect-targets/src/detect/windows.rs
Fixed #642
* Add new dep windows-sys v0.42.0 for win only
* Add new dep windows-dll v0.4.1 for win only
* Add x86_64 fallback targets for windows
* Add x86 fallback targets for windows
* Add arm32 fallback targets for windows
* Add arm64 fallback targets for windows
* Add gnu/gnu-llvm fallback targets for windows
=> detect-targets: Add fallback to windows

install-from-binstall-release.sh
Closes https://github.com/cargo-bins/cargo-binstall/issues/1122
Confirmed locally on macOS 12.5.1.
=> Use `uname -s` for install script compatibility with outdated macOS GNU utils

.github/dependabot.yml, .github/workflows/upgrade-transitive-deps.yml
for upgrading transitive dependencies.
While dependabot is great, it opens one PR for each of these transitive dependencies, which makes merging harder:
- have to approve every PR
- have to click merge when ci is done
it also creates merge queue runs and commits to main, thus creates a lot of unused caches and unnecessary CI runs.
This PR creates `upgrade-transitive-deps.yml` that creates one PR for all transitive change per-day.
It also configures dependabot to only `increase-if-necessary`, same as library crates.
Since we have several library crates in our workspace, this would mean that we would have less unnecessary deps bump on these library crates.
=> dep: Add new workflow `upgrade-transitive-deps.yml`

.github/dependabot.yml
for direct dependencies since compatible updates is already covered by `update-transitive-deps.yml`.
=> dependabot: Only create PR for incompatible updates

crates/binstalk-downloader/src/gh_api_client.rs, crates/binstalk-downloader/src/gh_api_client/request.rs
- Increase `DEFAULT_RETRY_DURATION` to 5 minutes, since GitHub enforces rate limit on an hourly basis.
- Refactor `check_for_status` & `fetch_release_artifacts_restful_api`
- Optimize `percent_decode_http_url_path`: Avoid `percent_decode_str` if there is no `%` in the `input`.
=> `GhApiClient` misc improvements

.github/workflows/ci.yml
- Remove trigger on "auto merge" enablement, which is just annoying now with the merge queue and was only ever an additional workaround for the release PRs.
- Always run the PR CIs, don't ignore markdown files. That made it impossible to merge PRs that only touched those files (without bypassing requirements).
=> Fix PR CI triggers

.github/workflows/ci.yml, crates/bin/src/args.rs, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/certificate.rs, crates/binstalk-downloader/src/remote/tls_version.rs, crates/leon/Cargo.toml, justfile
- ci: Check feat powerset of leon & binstalk-downloader in `ci.yml`
- fix leon feature `cli`: Enable dep `miette` in feature `cli`
- fix binstalk-downloader when default feature is disabled and no other tls related feature is enabled (breaking change due to replace of `tls::Version` with newtype `TLSVersion`).
=> fix `leon` & `binstalk-downloader` bug relating to features

Cargo.lock, crates/bin/Cargo.toml, crates/binstalk-types/Cargo.toml, crates/binstalk/Cargo.toml
Also bump strum_macros v0.24.3 => v0.25.0
[strum and strum_macros v0.25.0 changelog][1]
[1]: https://github.com/Peternator7/strum/blob/master/CHANGELOG.md
=> dep: Bump strum v0.24.1 => v0.25.0

Cargo.lock, crates/binstalk/Cargo.toml, crates/binstalk/src/bins.rs, crates/binstalk/src/errors.rs, crates/binstalk/src/fetchers.rs, crates/binstalk/src/fetchers/gh_crate_meta.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/helpers/target_triple.rs, crates/binstalk/src/ops/resolve.rs
Fixed https://github.com/cargo-bins/cargo-binstall/issues/775
- Add dep target-lexicon v0.12.7
- Add `target-{family, arch, libc, vendor}` to
`package.metadata.binstall`.
For `{universal, universal2}-apple-darwin`, the `target-arch` is set to
`universal`.
=> feat: Add more variables for template

.github/scripts/release-pr-template.ejs, .github/workflows/ci.yml, .github/workflows/release.yml
Fixed #1046
so that we don't have to manually run `cargo-publish` after the CI is merged.
=> ci: Publish to crates.io in `release.yml` after tagging

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/lib.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/errors.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/helpers/cargo_toml_workspace.rs, crates/binstalk/src/helpers/git.rs, crates/binstalk/src/helpers/git/progress_tracing.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/resolve.rs, crates/normalize-path/src/lib.rs, e2e-tests/git.sh, e2e-tests/manifests/workspace/Cargo.toml, e2e-tests/manifests/workspace/b/c/d/e/f/Cargo.toml, e2e-tests/manifests/workspace/crates/a/b/c/d/e/cargo-binstall/Cargo.toml, e2e-tests/manifests/workspace/crates/a/b/c/d/e/cargo-watch/Cargo.toml, justfile
=> feat: Support install directly from git repo

.github/workflows/release-pr.yml, .github/workflows/release.yml
Run `cargo-publish` without `--no-verify` to verify the publish is valid and does not depend on unpublished crates in job tag of workflow `release.yml`, which could be caused by incorrect merge order.
Also, install `cargo-semver-checks` using `taiki-e/install-action@v2` in job make-release-pr of workflow `release-pr.yml`, since `cargo-bins/release-pr@v2` would try to use `cargo-binstall` for installing `cargo-semver-checks`, but we did not explicitly require `taiki-e/install-actions@v2` to install `cargo-binstall`, so `release-pr` could fallback to `cargo-install` which is just too slow.
=> ci: Verify before publishing

Cargo.toml, justfile
After the merge of https://github.com/cargo-bins/cargo-binstall/pull/1184, CI now takes 11m just to shallow clone
crates.io git index, which means that our user using alternative git
index would also be quite slow.
This commit speeds it up by building all dependencies with `-O3` in dev
and release build.
=> Speedup prebuilt binary

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/install_path.rs, crates/binstalk-manifests/src/cargo_config.rs, crates/binstalk/src/errors.rs, e2e-tests/registries.sh, justfile
Fixed #885
Now we can take advantage of new argument `--registry` and env overrides:
- `CARGO_REGISTRIES_DEFAULT` if `--registry` is not specified
- `CARGO_REGISTRIES_{registry_name}_INDEX` for the registry index url
We can also read from `.cargo/config.toml` for:
- default registry and registries configurations
- additional CA bundle `http.cainfo`
=> Support `--registry` and more options from `.cargo/config.toml`

Cargo.lock, crates/bin/Cargo.toml, crates/binstalk/Cargo.toml, justfile
for targets:
- x86_64-apple-darwin
- aarch64-apple-darwin
- x86_64-unknown-linux-gnu
- x86_64-unknown-linux-musl
which will use `zlib-ng` to speedup decompression and use assembly
version for sha1 checksum calculation on supported CPU.
Also enable feature `zlib-ng` on windows and
- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl
#1184 adds e2e test that shallow clones the crates.io git index, which takes 11m just to clone the index in CI.
=> speedup git shallow cloning: Enable `gix/max-performance`

crates/binstalk-downloader/src/download.rs
Replace use of `PhantomData::default()` in `src/download.rs` with `PhantomData` since it is a unit struct.
=> Fix clippy warning in `binstalk_downloader`

Cargo.toml
=> Set opt-level for `{binstall, tokio}-tar` to `"z"`

Cargo.toml
Splitting too many codege-units would actually takes longer to compile due to overhead of parallelism in backend.
Also, our CI does not have that many CPU cores to take advantages of.
=> Optimize `profile.dev`: Set `codege-units` to 32

Cargo.lock, crates/binstalk/Cargo.toml, crates/binstalk/src/fs.rs
to speedup copy operation `atomic_install*`.
=> Use `reflink_copy::reflink_or_copy` in `fs::atomic_install*`

crates/bin/src/args.rs, justfile
and set `BINSTALL_RATE_LIMIT` to `100/1` on CI.
Fixed #1196
=> feat: Read `--rate-limit` from env `BINSTALL_RATE_LIMIT` as a fallback

crates/binstalk/src/drivers/registry/git_registry.rs, crates/binstalk/src/helpers/git.rs
[Clones of the crates-index are very slow on windows.](https://github.com/Byron/gitoxide/discussions/931#discussion-5405751), and `cargo` is also not doing them but uses bare clones instead.
> > If you point me to the place where the full checkout is needed, I could probably figure out the rest from there as long as a git repository is present that contains the crates-index. It's not a big deal at all (probably not even famous last words ;)).
> 
> Here is the [code we use for cloning and checkout](https://github.com/cargo-bins/cargo-binstall/blob/main/crates/binstalk/src/helpers/git.rs).
> 
> It is then used in [`git_registry.rs`](https://github.com/cargo-bins/cargo-binstall/blob/963e9e97add0a681f117fe21c6b3fde074706ac7/crates/binstalk/src/drivers/registry/git_registry.rs#L40) and …
=> avoid worktree checkouts

justfile
`100/1` slows CI down to a snail when getting rate limited by GitHub.
=> CI: Relax rate limit to `30/1`

Cargo.lock, crates/bin/Cargo.toml, crates/bin/build.rs, crates/bin/src/args.rs, crates/bin/src/main.rs, crates/binstalk/src/lib.rs
that provides more information:
```
cargo-binstall: 1.0.0
build-date: 2023-07-18
build-target: aarch64-apple-darwin
build-features: default,fancy_no_backtrace,git,rustls,static,trust_dns,zstd_thin
build-commit-hash: https://github.com/cargo-bins/cargo-binstall/commit/39d8cfc07f2253080ce997e620406c2994dced25
build-commit-date: 2023-07-18
rustc-version: 1.71.0
rustc-commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
rustc-llvm-version: 16.0
```
Fixed #627
=> feat: Support `--verbose --version`/`-vV`

.github/workflows/release-pr.yml
Checking semver caused [release-pr](https://github.com/cargo-bins/cargo-binstall/actions/runs/5587299243) to failed when requesting new cargo-binstall release.
cargo-binstall is not a library crate so there's no need to check it.
=> Fix `release-pr.yml`: Do not `check-semver` for cargo-binstall release

crates/detect-targets/src/detect/macos.rs
Now `detect_targets` would fallback to `x86_64h-apple-darwin` on `aarch64-apple-darwin`.
It also provides fallback to `x86_64h-apple-darwin` to `x86_64-apple-darwin` and universal targets.
=> feature: Add fallback `x86_64h-apple-darwin` and fallback for it

justfile
Try to fix recent `Illegal instructions` happened in CI.
=> Disable `sha1-asm` or `zlib-ng` on x86_64 linux

.github/workflows/release-build.yml, justfile
instead of `x86_64-apple-darwin` for better optimization since any machine that support universal support x86_64h.
=> ci: Build MacOS universal exe from x86_64h-apple-darwin

crates/binstalk/src/helpers/cargo_toml_workspace.rs, crates/binstalk/src/ops/resolve.rs, crates/binstalk/tests/parse-meta.rs
Previously it will load the root `Cargo.toml` and treat it as the manifest for the crate, now it will check its `package.name` and would search for the workspace if the `package.name` does not match the crate name.
=> feat: Support passing workspace to `--manifest-path`

justfile, zigbuild-requirements.txt
ziglang 0.11 causes link failure in our CI
=> Fix CI: Require ziglang < 0.11

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/utils.rs
By accepting `&mut dyn DataVerifier` for users to pass any callback that uses `digest::Digest`/`digest::Mac`, `sigstore` or whatever they want.
=> feat: Support data verification in `Download`

Cargo.lock, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/gh_api_client.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/delay_request.rs, crates/binstalk/src/drivers/registry.rs, crates/binstalk/src/fetchers/quickinstall.rs, crates/binstalk/src/helpers/remote.rs
=> Fix too many 429 response

.github/workflows/ci.yml, .github/workflows/release-build.yml
Which guarantees:
- faster linking on all targets when `cargo-zigbuild` is not used
- allow cross-lang-lto to be enabled
=> Use `rust-lld` in CI

.github/workflows/ci.yml, .github/workflows/release-build.yml
Reverts cargo-bins/cargo-binstall#1253
It's not really working as mentioned in #1256
=> Revert "Use `rust-lld` in CI"

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/async_tar_visitor.rs, crates/binstalk-downloader/src/download/zip_extraction.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/request_builder.rs, crates/binstalk-downloader/src/utils.rs
I planned to replace `futures-util` with `futures-lite`, but it turns out that `reqwest` actually depends on `futures-util`, so there is no point removing it and introduce yet another dependency.
=> Remove dep `futures-lite` from `binstalk-downloader`

crates/bin/src/entry.rs
Try bogth original and upper-case version as mentioned in https://github.com/cargo-bins/cargo-binstall/pull/1253#issuecomment-1667021470
=> Fix reading env `CARGO_REGISTRIES_{registry_name}_INDEX`

.github/workflows/ci.yml, .github/workflows/release-build.yml, Cargo.lock, crates/bin/Cargo.toml, crates/binstalk-downloader/Cargo.toml, crates/binstalk/Cargo.toml, justfile
For dev and release build, so that pre-built binaries of `cargo-binstall` can utilize http3 protocol.
=> Enable unstable feature `reqwest/http3` in CI

.github/workflows/install-script.yml, .github/workflows/shellcheck.yml, install-from-binstall-release.sh
Fixed #1254
and also add CI for installation script.
=> Fix installation script on MacOS

Cargo.lock, crates/bin/src/entry.rs, crates/binstalk-downloader/src/lib.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/drivers/registry.rs, crates/binstalk/src/drivers/registry/common.rs, crates/binstalk/src/drivers/registry/crates_io_registry.rs, crates/binstalk/src/drivers/registry/git_registry.rs, crates/binstalk/src/drivers/registry/sparse_registry.rs, crates/binstalk/src/helpers.rs
Fixed #1183
Since the crate tarball could be downloaded from a different set of servers than where the cargo registry is hosted, verifying the checksum is necessary to verify its integrity.
=> feat: Verify cksum of crate tarball from cargo registry

.github/workflows/gh-action.yml, README.md, action.yml
I'd like to suggest adding `action.yml`, which makes it easier for users to install `cargo-binstall` in GitHub Action workflows, for example:
```yml
steps:
- uses: cargo-bins/cargo-binstall@main
- run: cargo binstall -y ripgrep
```
see complete example [here](https://github.com/smallstepman/eseses/blob/f64ab0af614eab84cb4489a306b30de66e8e19e0/.github/workflows/test.yml) and [the result of running that workflow](https://github.com/smallstepman/eseses/actions/runs/5807859507).
I'm aware of https://github.com/taiki-e/install-action, but I'd prefer to:
- install directly from the source
- rely on organizations rather than individual developers
- to not have to conduct a security review of GitHub Actions that contains a few thousand lines of code and config files
```console
❯ git clone …
```
=> Add GitHub Action declaration for installing `cargo-binstall`

Cargo.lock, crates/binstalk/Cargo.toml
In tokio v1.30.0, MSRV is bumped to rust 1.63 and all `const_new` methods in `tokio::sync` are now always available, so there is no need to enable feat `parking_lot`.
=> dep: Bump tokio to v1.30.0 & disable feat `parking_lot`

crates/detect-targets/src/detect/macos.rs
Partially resolve #1277
Run `arch -arch x86_64h /usr/bin/true` to decides whether fallback is feasible.
=> Fix `aarch64-apple-darwin` fallback to `x86_64h`

.github/workflows/release-build.yml, justfile
To makre sure it can run on pre-haswell Intel CPUs.
Fixed #1277
=> Include `x86_64` & `x86_64h` in universal apple pre-built binary

.github/workflows/ci.yml
Set `CARGO_PROFILE_RELEASE_CODEGEN_UNITS` to 4
since 1024 units are too many and our CI only have 2-3 cores.
=> Speedup `ci.yml`: Set codegen-units to 4

Cargo.lock, Cargo.toml, crates/bin/src/logging.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/drivers/registry.rs, crates/binstalk/src/drivers/registry/common.rs, crates/binstalk/src/drivers/registry/crates_io_registry.rs, crates/binstalk/src/drivers/registry/git_registry.rs, crates/binstalk/src/drivers/registry/sparse_registry.rs, crates/binstalk/src/drivers/registry/vfs.rs, crates/binstalk/src/drivers/registry/visitor.rs, crates/binstalk/src/errors.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/ops/resolve.rs, crates/binstalk/tests/parse-meta.rs, crates/cargo-toml-workspace/Cargo.toml, crates/cargo-toml-workspace/LICENSE-APACHE, crates/cargo-toml-workspace/LICENSE-MIT, crates/cargo-toml-workspace/src/lib.rs
To reduce codegen time of `binstalk` and also enable others to reuse this crate.
=> Refactor: Extract `cargo_toml_workspace` as a new crate

Cargo.lock, Cargo.toml, crates/atomic-file-install/Cargo.toml, crates/atomic-file-install/LICENSE-APACHE, crates/atomic-file-install/LICENSE-MIT, crates/atomic-file-install/src/lib.rs, crates/bin/src/logging.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/lib.rs
To speedup codegen of `binstalk` and also publish a new crate that could be reused.
=> Refactor: Extract mod `fs` as crate `atomic-file-install`

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/git.rs, crates/binstalk-downloader/src/git/cancellation_token.rs, crates/binstalk-downloader/src/git/progress_tracing.rs, crates/binstalk/src/drivers/registry/git_registry.rs, crates/binstalk/src/ops/resolve.rs
To make sure users can cancel git operation via signal, e.g. when the git operation fail or users no longer want to install.
=> feat: `git::Repository` cancellation support

crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/bin_util.rs, crates/bin/src/lib.rs, crates/bin/src/signal.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/helpers.rs, crates/binstalk/src/lib.rs
- Make `binstalk::bins` private, implemented https://github.com/cargo-bins/cargo-binstall/issues/1194#issuecomment-1674841097
- Move mod `signal` into `crates/bin` implemented https://github.com/cargo-bins/cargo-binstall/issues/1194#issuecomment-1674836320
- Make items in `crates/bin/src/lib.rs` private if possible to reduce its API generation time.
=> Refactor to reduce compilation time

Cargo.lock, Cargo.toml, crates/bin/src/args.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-registry/Cargo.toml, crates/binstalk-registry/LICENSE-APACHE, crates/binstalk-registry/LICENSE-MIT, crates/binstalk-registry/src/common.rs, crates/binstalk-registry/src/crates_io_registry.rs, crates/binstalk-registry/src/git_registry.rs, crates/binstalk-registry/src/lib.rs, crates/binstalk-registry/src/sparse_registry.rs, crates/binstalk-registry/src/vfs.rs, crates/binstalk-registry/src/visitor.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/drivers.rs, crates/binstalk/src/errors.rs, crates/binstalk/src/helpers.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/ops.rs
To speedup codegen of `binstalk` and enable it to be reused.
=> Refactor: Extract new crate `binstalk-registry`

Cargo.lock, Cargo.toml, crates/bin/Cargo.toml, crates/bin/src/entry.rs, crates/bin/src/logging.rs, crates/binstalk-bins/Cargo.toml, crates/binstalk-bins/src/lib.rs, crates/binstalk-fetchers/Cargo.toml, crates/binstalk/Cargo.toml, crates/binstalk/src/errors.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/ops/resolve.rs, crates/binstalk/src/ops/resolve/resolution.rs, e2e-tests/no-track.sh
To reduce `binstalk` codegen and enable reuse of it.
=> Refactor: Extract new crate `binstalk-bins`

crates/binstalk-registry/Cargo.toml, crates/binstalk-registry/src/crates_io_registry.rs, crates/binstalk-registry/src/lib.rs
Fixed #1295
The 1 request per second rate-limit is too strict and it makes `cargo-binstall` very slow when resolving many crates in parallel.
Relying on the rate-limit in `binstalk_downloader::remote::Client` should be good enough.
=> `binstalk-registry`: Rm rate-limit for crates.io registry

crates/binstalk-downloader/Cargo.toml
Fix use of `native-tls` and `git`, make sure that `gix` actually uses `native-tls` in this scenario.
=> Fix `binstalk-downloader` feature activation

crates/binstalk/src/ops/resolve.rs
So that users know that this is an upstream issue and will report to upstream.
=> Add `error` logging if achieve doesn't contain bin required

.github/workflows/ci.yml, .github/workflows/release.yml
Add a unique value to `concurrency.group` in `ci.yml` to prevent it from being cancelled when releasing crates.
=> ci: Fix `release.yml` being cancelled due to `ci.yml`

crates/binstalk-registry/Cargo.toml, crates/binstalk-registry/src/crates_io_registry.rs, crates/binstalk-registry/src/lib.rs
Fixed #1310
Also add rename `fetch_crate_cratesio` => `fetch_crate_cratesio_api` and put it behind a new feature `crates_io_api`.
=> binstalk-registry: Use crates.io sparse index by default

.github/workflows/release.yml
Since the merge_queue requires every PR to be tested, there is no need to run the test again in `release.yml`.
=> ci: Speedup `release.yml` by removing job `test`

Cargo.toml
Since some of our dependencies still uses edition 2018, we need to explicitly specify the resolver.
=> Use resolver 2 for cargo workspace

crates/binstalk-downloader/src/gh_api_client.rs
The gnu cargo audit release was duplicated instead of the gnu and musl releases both being represented.
=> Fix binstalk-downloader test: duplicated gnu cargo audit

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/gh_token.rs, crates/bin/src/git_credentials.rs, crates/bin/src/lib.rs, crates/binstalk-downloader/src/gh_api_client.rs
Fixed #1333
- Rm dep `gh-token` since it is broken and we can simply run `gh auth token` in `cargo-binstall` instead.
- binstalk-downloader: Make sure GitHub token is at least 40B long and other than the `_`, composes of only alphanumeric characters.
- Warn on failure to read `git/credential` files
- Optimize `try_from_home` to avoid heap allocation of `PathBuf`
=> Fix GitHub token auto discovery

crates/binstalk-downloader/Cargo.toml
Feature git is removed from binstalk-downloader, however we still enable it on docs.rs build.
=> Fixed binstalk-downloader docs.rs build

crates/bin/src/args.rs, crates/binstalk/src/ops/resolve/resolution.rs
Fixed https://github.com/cargo-bins/cargo-binstall/issues/1336
- Log target of the pre-built binaries which will be installed
- Fix args parsing: quiet & verbose cannot be set at the same time
- feat: Implies `--log-level debug` if `--verbose` is set
=> feat: Improve resolution logging and verbose logging

crates/detect-targets/src/detect.rs, crates/detect-targets/src/detect/linux.rs
Fixed #1329
- Refactor: Create `linux::detect_alternative_targets` to reuse code from other targets
- Run `/lib/ld-linux-{cpu_arch}.so.1 --version` for checking glibc support instead of running `ldd --version` since it could be non-std glibc installation and does not provide `/lib/ld-linux-{cpu_arch}.so.1`
- Check for non-std glibc and add fallback target `{cpu_arch}-{distro_name}-linux-gnu{abi}`
- Add `{cpu_arch}-{distro_name}-linux-musl{abi}` fallback for musl libc, specially for Alpine since it has a `/lib/ld-musl-{cpu_arch}.so.1`
- For unknown libc flavor, check for the target provided before fallback to musl
- Support glibc on musl target
- Always run checks for both glibc and musl, since they can be both installed at the same time
=> feat `detect-targets`: Improve support of non-std glibc/musl

.github/workflows/ci.yml, crates/detect-targets/Cargo.toml, crates/detect-targets/src/detect.rs, crates/detect-targets/src/detect/linux.rs, crates/detect-targets/src/main.rs, justfile, test-detect-targets-musl.sh
Fixed the bug introduced #1343
- Fix `linux::detect_targets`: `guess_host_triple` could return gnu suffix on musl system, so always check that in `detect_targets` instead of using the target provided by `guess_host_triple`
- Remove distro-specific targets since it breaks fallback to `cargo`
- Fix `linux::detect_targets` on Alpine's gcompat version glibc
- Fix `linux::detect_targets` on Ubuntu where glibc is stored in `/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2`
- Add testing for `detect-targets`
- Add `package.metadata.binstall` for `detect-targets`
=> Fix `detect-targets` on Linux and add CI testing

.github/dependabot.yml
Fixed #1353
Merge all dependabot configuration for cargo into one, with directory setting to `/` so that it will check for dep updates for entire workspace while also updating lockfile in PR.
To prevent it from opening too many PRs, it's configured to run on every Saturday, after `upgrade-transitive-deps.yml` is run.
It will also group all dependencies into one PR to prevent opening too many PRs.
=> Fixed and simplify dependabot configuration

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/lib.rs, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/resolver.rs
This PR applies the fix from @GNQG + some formatting changes.
Patch applied: https://github.com/GNQG/cargo-binstall/commit/cb40519ff6e02e624abb25491b0f86ccb829e478
Fixes #1339
By default, `trust-dns` loops through all available interfaces and tries to use them, but when you have applications installed such as VMware or VirtualBox, it creates interfaces that resolve to the loopback address. Given that `trust-dns` has a timeout of 5s and then retries many times, it becomes really slow. This PR adds a custom DNS resolver struct that instructs `trust-dns` to only query the default network interface (which is either "WiFi" or "Ethernet", most of the time).
=> fix: use custom DNS resolver

.github/workflows/ci.yml, crates/detect-targets/src/detect/linux.rs
Fixed #1375 and fixed #1378
glibc 2.31 does not support `--version`, so we need to detect and fallback to passing an executable linked with that glibc to check if it is indeed glibc.
=> Fix `detect-targets` on ubuntu 20.04, glibc 2.31

.github/scripts/ephemeral-gen.sh, .github/scripts/ephemeral-sign.sh, .github/workflows/release-build.yml, .github/workflows/release.yml, SIGNING.md
This uses an ephemeral key.
It writes the `[signing]` section to the Cargo.toml just before publish, so the Cargo.toml in the source remains without, which makes `--git` installs work (just without verifying signatures).
It uses rsign2 so we can install it via binstall (dogfooding!).
=> Sign our releases

Cargo.lock, crates/bin/src/logging.rs, crates/binstalk/Cargo.toml, crates/detect-targets/Cargo.toml, crates/detect-targets/src/detect.rs, crates/detect-targets/src/detect/linux.rs, crates/detect-targets/src/main.rs
=> Investigate incorrect target detection

Cargo.lock, crates/cargo-toml-workspace/Cargo.toml, crates/cargo-toml-workspace/src/lib.rs
`cargo-toml-workspace` should not depend on and be coupled with `binstalk-types` but instead be a generic crate that can be used outside `cargo-binstall`.
=> Refactor `cargo-toml-workspace`: Rm dep on `binstalk-types`

.github/scripts/ephemeral-crate.sh, .github/scripts/ephemeral-gen.sh, .github/scripts/ephemeral-sign.sh, .github/workflows/ci.yml, .github/workflows/release-build.yml, .github/workflows/release-cli.yml, .github/workflows/release-packages.yml, .github/workflows/release.yml, SIGNING.md
(Set 1.3.2 back as latest and yanked 1.4.0 so it doesn't get used.)
- Knew there was a reason I was going with artifacts for the key: [github actions can't pass outputs into secrets](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjobs_idoutputs)
- Uses `rage` to encrypt the key instead of using minisign's janky password thing
- Changes the workflow so that we once again publish the crate _after_ the github release has built successfully
- Uploads all the packages to a prerelease, then promotes that prerelease to latest as the last step, so the release is always complete when it's published, which means that the action will always work
- Those changes mean that we can finally achieve what we wanted all along: dry-run the entire release process!
=> Fix release build again

.github/workflows/release-cli.yml
Had this idea just after the build finally passed: when not releasing, we can cargo-package and upload the `.crate` file as artifact to check it if wanted.
=> Upload packaged crate

.github/scripts/ephemeral-gen.sh, .github/scripts/ephemeral-sign.sh, .github/workflows/release-cli.yml, .github/workflows/release-packages.yml
=> Fix `release-packages` and `release-cli` workflow

.github/workflows/ci.yml
Without this we get much less useful output if these tests fail.
=> .github: build detect-targets with cli-logging

.github/workflows/ci.yml
Without this we get much less useful output if these tests fail.
=> .github: build detect-targets with cli-logging (#1428)

crates/binstalk/src/ops/resolve/resolution.rs, crates/detect-targets/src/desired_targets.rs
which is guaranteed to work, instead of providing a custom `--target` from `detect-targets`.
The one from `detect-targets` might report musl even if the `rustc` reports gnu, since OSes like NixOS could use a custom glibc location that prevent glibc binaries built for other OSes be run for them.
However, if we are compiling the crate and `rustc` defaults to glibc, then it should be guaranteed to work.
=> Fix fallback to `cargo-install`: Use the default target unless user override

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/remote/resolver.rs
Since we no longer enables `reqwest/trust-dns-resolver` anymore, we don't need to keep this dependency is sync with upstream `reqwest`.
=> Bump dep trust-dns-reslver to v0.23.0

.github/workflows/ci.yml
For PRs opened by contributors who are not part of the cargo-bins team and for PRs opened by dependabot, they cannot access the secrets, thus signing will always fail.
Skipping release-dry-run on pull_request would fix that for them, while retaining the signing stage on merge_queue and on main to ensure that the release workflow is working.
It will also speedup CI for PR.
=> CI: Skip release-dry-run on pull_request

install-from-binstall-release.ps1
In some unusual configurations (perhaps something to do with Docker), `CsSystemType` on the result of `Get-ComputerInfo` can be null, preventing the script from running. Switch to using the environment variable `PROCESSOR_ARCHITECTURE` instead – if this is read from the machine environment variables instead of the process ones, it indicates the architecture of the machine.
This is also faster as `Get-ComputerInfo` can take several seconds to run.
I’ve validated this against my internal build pipeline, which I unfortunately cannot share.
=> Change Powershell architecture detection

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/remote.rs, crates/binstalk-downloader/src/remote/resolver.rs
It's renamed to hickory-resolver.
Also enabled new feature `hickory-resolver/dns-over-h3` if `rustls` is enabled.
=> dep: Update trust-dns-resolver v0.23.0 => hickory-resolver 0.24.0

crates/bin/src/entry.rs, crates/bin/src/gh_token.rs, crates/bin/src/git_credentials.rs
Fixed #1476
If `gh auth token` executed successfully and binstall obtained a gh token from it, then there's no reason to issue any warning msg.
Only when binstall cannot read from `.git-credential` and `gh auth token` failed does binstall need to issue warning.
=> Rm unnecessary warning msg "Failed to read git credential file"

.github/actions/just-setup/action.yml
This can be helpful in two situations:
- If `cc` is bumped to a new release, then all the `*-sys` crates will be rebuilt even if their source doesn't change. Caching zig global_cache would avoid expensive rebuilds.
- For target `x86_64h-apple-darwin`, it uses build-std which means the rust cache is quite ineffective (only build-dependencies are cached), so we would also need zig global_cache to avoid rebuilding c dependencies in CI.
=> CI: Cache zig global_cache to speedup build

.github/workflows/release-cli.yml
If dependencies of `cargo-binstall` is bumped, then `cargo-publish` dry run will fail since the dependency has not published yet, so to fix this `cargo-publish` dry run is removed and `cargo-package` is now run with verification.
This PR also uses `just-setup` to cache rust/zig compilation and disables all features to reduce dependencies pulled in during `publish` step of `release-cli.yml`.
=>  Fix `release-cli.yml`: Do not dry run cargo-publish

.github/workflows/ci.yml, .github/workflows/release-cli.yml
If there's no crate to publish, do not dry-run `cargo-publish`.
Only dry-run `cargo-publish` on crate to be published to avoid `cargo-publish` error on `cargo-binstall` when one of its direct dependencies is bumped.
=> Fix CI: Dry-run `cargo-publish` on crate to be published

install-from-binstall-release.ps1
I have `$env:CARGO_HOME` set and just had this warning tell me I was missing the wrong path from my path. This makes the ps1 script do the same thing as the sh script and look in `$env:CARGO_HOME` if present.
I originally used `??` to null coalesce, but switched to just an `if` expression since `??` was only added in pwsh 7 (PowerShell Core, the cross platform one you need to install), thus isn't available in Windows Powershell. The `if` works in Windows PowerShell as well.
=> Use $Env:CARGO_HOME in ps1 install script

README.md
[Rendered](https://github.com/cargo-bins/cargo-binstall/tree/passcod-patch-1#readme)
- Reorders sections to show Binstall's value upfront
- Clarifies and simplifies language
- Updates the sample output
- Includes cargo-run-bin (fixes #1514)
- Places the github actions in more prominence in the Install section (fixes #1342)
- Unifies appellation by consistently using the "Binstall" name except for commands
- Changes the arch labels in the install table to reflect common/official usage
=> Renew readme

crates/binstalk-registry/src/lib.rs
This is a minor nit, but `cargo` itself tolerates a trailing slash at the end of the registry index URL, automatically trimming it before building URLs for sparse interaction. `cargo-binstall` does not, and thus, if a registry index URL includes a trailing slash, it sends queries to a URL with a double slash. For JFrog Artifactory, this results in an error being returned:
```console
❯ cargo binstall --locked --registry private my-tool
INFO resolve: Resolving package: 'my-tool'
ERROR Fatal error:
× For crate mytool: could not GET https://example.com/artifactory/api/cargo/cargo-local/index//config.json: HTTP status client
│ error (400 Bad Request) for url (https://example.com/artifactory/api/cargo/cargo-local/index//config.json)
├─▶ could not GET …
```
=> fix: remove a trailing slash in registry index URL

crates/bin/src/args.rs
Adds an environment variable for the `--strategies` parameter to control strategies on a per environment level, rather than per command.
=> feat: Add strategies environment variable

justfile
To fix the error in #1563 CI and also re-enable zlib-ng for x86_64 linux to improve its performance since it is one of the most used targets.
=> Disable zlib-ng for aarch64 linux and re-enable it for x64 linux

.github/workflows/install-script.yml, install-from-binstall-release.sh
Adds an additional `elif [ "$OS" = "Windows_NT" ]` check to then use the Windows binaries.
<details><summary>OLD</summary>
Now this works on Windows:
```sh
jcbhm@PIG-2016 MINGW64 ~
$ curl -L --proto '=https' --tlsv1.2 -sSf https://github.com/jcbhmr/cargo-binstall/raw/patch-1/install-from-binstall-release.sh | bash
```
It uses `powershell -c` to directly run the code that I copied from https://github.com/cargo-bins/cargo-binstall/blob/main/install-from-binstall-release.ps1. You could also do this:
```sh
powershell -c 'Set-ExecutionPolicy Unrestricted -Scope Process; iex (iwr "https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.ps1").Content'
```
if you so choose.
Previously when using Git Bash it wouldn't work:
```sh
jcbhm@PIG-2016 MINGW64 ~
$ …
```
=> Fix install-from-binstall-release.sh for Git Bash users on Windows

crates/binstalk/src/ops/resolve.rs
Ran into this randomly, and got hung up for a second trying to understand the word `withupstream`
=> Fix missing spaces in error log

crates/bin/Cargo.toml
Since the one on GitHub has changed.
=> Update crates.io description for cargo-binstall

crates/simple-git/src/lib.rs
Forward it to `<gix::Url as Display>::fmt` now that `gix::Url` implements `Display`
=> Update `<simple_git::GitUrl as Display>::fmt` impl

.github/workflows/ci.yml, .github/workflows/gh-action.yml, .github/workflows/install-script.yml, .github/workflows/release-packages.yml, e2e-tests/subcrate.sh
`macos-14` provides 3-core M1, 7G mem and 14G stroage, while `macos-latest` (`macos-13` as of writing) provides 4-core intel, 14G mem and 14G storage.
While the memory is cut by half and core count reduce by 1, I believe that it would still speedup the CI since M1 is much more powerful than previous Intel CPU used in `macos-13`.
It would also allow us to run tests on aarch64-apple-darwin and on universal-apple-darwin, if necessary.
=> CI: Use runner `macos-14` which uses M1 machine

Cargo.lock, crates/binstalk-downloader/Cargo.toml
Related: https://github.com/nabijaczleweli/cargo-update/issues/250
=> Fix: Load system-wide native cert on rustls

.github/workflows/release-pr.yml
leon-macros is a proc-macro crate and cargo-semver-checks cannot perform semver checks on proc-macro crates.
=> Fix release-pr.yml: Do not run semver-checks for leon-macros

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/remote/resolver.rs, crates/binstalk-registry/Cargo.toml, crates/binstalk/Cargo.toml
reqwest 0.11.27 is still used in gix, but it will be upgraded in next gix release.
=> Bump dep reqwest in binstalk-downloader from 0.11.26 to 0.12.0

Cargo.lock, crates/binstalk-downloader/Cargo.toml
to support compression using zstd.
Also enable `http2` (which is now enabled by other deps of this crate).
Fixed #1666
=> Bump reqwest to 0.12.4 and enable feature zstd

.github/workflows/ci.yml, .github/workflows/release-packages.yml
According to [GitHub Rate limits for the REST API doc](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users), personal access token has rate-limit of 5,000 requests per hour, the builtin `secrets.GITHUB_TOKEN` only has 1,000 requests per hour per repository.
So I setup `secrets.CI_TEST_GITHUB_TOKEN` and use it for all testing in `ci.yml` to avoid hitting the rate limit of `secrets.GITHUB_TOKEN`, once the rate limit is hit the CI would become either very slow or straight up fail.
I also setup `secrets.CI_RELEASE_TEST_GITHUB_TOKEN` for e2e-test run in `release-packages.yml`.
Other tasks (taiki-e/install-action, creating new releases/tags/prs, etc) would still use the `secrets.GITHUB_TOKEN`, since …
=> Speedup ci by using personal access token for testing

crates/binstalk-fetchers/src/lib.rs
=> Fix binstalk_fetchers::FetchError definition

.github/workflows/ci.yml
When there are multiple crates, it would be in multiple lines, breaking github output
=> Fix job changed-files in ci.yml

.config/nextest.toml, Cargo.lock, crates/binstalk-git-repo-api/Cargo.toml, crates/binstalk-git-repo-api/src/gh_api_client.rs, crates/binstalk-git-repo-api/src/gh_api_client/common.rs, crates/binstalk-git-repo-api/src/gh_api_client/release_artifacts.rs, crates/binstalk-git-repo-api/src/gh_api_client/repo_info.rs
- Share `remote::Client` between tests when in `cargo-test`
- Run rate-limited tests in serial
- Update client-side rate limit to 1 request per 300ms
=> Speedup binstalk-git-repo-api unit testing

crates/binstalk/src/ops/resolve.rs, e2e-tests/live.sh
This is an alternative idea to solve #1721.
It makes much more sense to me to prefer official binaries (i.e. ones resolved from an "earlier strategy") with a secondary target (e.g. `musl` instead of `gnu` on linux) over binaries from a later strategy (quickinstall).
I have only quickly rummaged through the source code and confirmed it works with installing `jj-cli` from the official release page instead of quickinstall, I don't know if this impacts something else.
=> fix(resolve): prefer official binaries

.github/workflows/ci.yml
- Fix job changed-file in ci.yml
- Do not run job e2e-tests on PR
- Provide GITHUB_TOKEN fallback if the secrets is not accessible
=> Fix ci and improve efficiency

crates/binstalk-fetchers/src/gh_crate_meta.rs, crates/binstalk-registry/src/visitor.rs, crates/binstalk/src/ops/resolve.rs, e2e-tests/live.sh, rust-toolchain.toml
When there is a single binary declared in the manifest and it differs from the package name, add it to the list of handles used for pre-built artifact fetching.
Fixes #988
=> Use binary name when searching for artifacts

.github/workflows/ci.yml
All commits should be submit via PR, and merge_queue already run ci.yml, with up-to-date source code.
=> Do not run ci.yml on push to main

.github/workflows/ci.yml, .github/workflows/release-cli.yml, .github/workflows/release.yml
Use latest stable Rust toolchain
Also stop running release-dry-run on release PR, it isn't helpful and only waste time.
=> CI: Fix publish

.github/workflows/ci.yml
Just to keep the cache hot while making sure cargo-binstall can compile on latest stable/nightly rust
=> Run ci.yml every Monday

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/gh_token.rs, crates/bin/src/git_credentials.rs, crates/binstalk-git-repo-api/Cargo.toml, crates/binstalk-git-repo-api/src/gh_api_client.rs, crates/binstalk/Cargo.toml, crates/binstalk/src/helpers.rs, crates/binstalk/src/helpers/lazy_gh_api_client.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/resolve.rs
- Make sure the token is zeroed out/erased on drop fixed #1761 
- Spawn  `gh auth token` as a task and only await it when `GhApiClient` is needed fixed #1733
=> Improve use of github token

.github/actions/just-setup/action.yml
Use transparent huge page, according to https://kobzol.github.io/rust/rustc/2023/10/21/make-rust-compiler-5percent-faster.html it gives a nice 5% speedup
=> Speedup Linux CI

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-git-repo-api/src/gh_api_client.rs, crates/binstalk-git-repo-api/src/gh_api_client/common.rs, crates/binstalk-git-repo-api/src/gh_api_client/release_artifacts.rs, crates/binstalk-git-repo-api/src/gh_api_client/repo_info.rs
reqwest 0.12.5 re-enabled http3 support, however with http3 support the future returnd from `reqwest` no longer implements `Sync`.
SInce `tokio::spawn` does not requore `Sync`, it's removed from the return future in `binstalk-git-repo-api`, however since it is breaking behavior I will report this to upstream.
=> Re enable h3 in reqwest and remove impl `Sync` on returned Future in `binstalk-git-repo-api`

.github/workflows/release-pr.yml
In case buliding of previous version fail due to new releases in upstream.
=> CI: Allow semver-check in `release-pr.yml` to be disabled via inputs

crates/binstalk-fetchers/Cargo.toml, crates/binstalk-fetchers/src/common.rs, crates/binstalk-fetchers/src/futures_resolver.rs, crates/binstalk-fetchers/src/gh_crate_meta.rs, crates/binstalk-fetchers/src/lib.rs, crates/binstalk-fetchers/src/quickinstall.rs, crates/binstalk/src/ops/resolve.rs
Creating too many requests is slower since cargo-binstall is very likely to be rate limited, and cargo-binstall actually has a preference on artifact discovery resolution, so many requests are just wasted/not used but slow down the one cargo-binstall want.
=> Run artifact discover in sequential instead of in parallel

install-from-binstall-release.sh
`uname -m` returns 'armv7l' on raspberry pi, but 'armv7' works just fine
=> Raspberry-pi

crates/binstalk-manifests/src/cargo_crates_v1.rs
It uses a private type so it should not have public visibility.
=> Mark binstalk_manifests::cargo_crates_v1::CratesToml::insert private

crates/binstalk-fetchers/src/lib.rs, e2e-tests/manifests/github-test-Cargo2.toml, e2e-tests/manifests/gitlab-test-Cargo.toml, e2e-tests/manifests/private-github-repo-test-Cargo.toml
Closes #1801, see #1803 for a more generic version.
Here I can add the test as the `GhApiClient` is never invoked.
=> fix: normalize GitHub URLs ending in .git to not ending in .git

Cargo.lock, crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk-fetchers/src/gh_crate_meta.rs, crates/binstalk-fetchers/src/lib.rs, crates/binstalk-fetchers/src/quickinstall.rs, crates/binstalk-types/Cargo.toml, crates/binstalk-types/src/cargo_toml_binstall.rs, crates/binstalk/src/ops/resolve.rs, e2e-tests/manifests/strategies-test-Cargo.toml, e2e-tests/strategies.sh
Fixed #1721
This allow the maintainer of the crate to disable certain strategies of cargo-binstall, to ensure that the source of the binary is from the one that maintainer provided.
=> Feature: SupportdDisable of strategies for crate using `Cargo.toml`

SUPPORT.md
=> Update doc in SUPPORT.md for disabled-strategies

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/binstalk-fetchers/src/quickinstall.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/ops.rs, crates/binstalk/src/ops/resolve.rs
=> Add new option to `--disable-telemetry` to disable quickinstall statistics collection

.github/workflows/release-plz.yml, release-plz.toml
This PR adds release-plz to release library crates automatically.
The existing release-system would require one PR for every release of library crates, which is very time consuming and waste a lot of energy on running CI.
It'd also require careful picking of order, as dependencies has to be released before dependents and the release PRs could also have merge conflicts.
It turns out that release-plz is the perfect solution for library crates, while as for cargo-binstall binary crate we'd continue to use our existing system, with manual triggering and manual changelog writing.
=> CI: Add release-plz to release library crates

.github/workflows/gh-action.yml, .github/workflows/install-script.yml, .github/workflows/release-cli.yml, .github/workflows/release-pr.yml
Pass GITHUB_TOKEN to whereever `cargo-binstall` is invoked, and prefer `CI_RELEASE_TEST_GITHUB_TOKEN`
=> Fix CI blocked due to cargo-binstall rate-limit

crates/bin/src/args.rs, crates/bin/src/entry.rs, crates/bin/src/main_impl.rs, e2e-tests/manifests/strategies-test-override-Cargo.toml, e2e-tests/strategies.sh
=> Fix: --strategies on CLI do not seem to override disabled-strategies in the manifest

release-plz.toml
Do not set release as latest, since that would break installation script/action.
=> Fix release-plz.toml

Cargo.lock, crates/binstalk-downloader/Cargo.toml, justfile
Remove workaround for ring 0.16 on `aarc64-pc-windows-msvc`, and a bunch of duplicate dependencies.
=> dep: Bump hickory-resolver to 0.25.0-alpha.2

README.md, crates/bin/src/args.rs
These changes describe the usage statistics collected when the `quickinstall` strategy is used by default, according to the discussion and details brought forward on https://github.com/cargo-bins/cargo-binstall/issues/1884. Both the project README and the CLI long help contain clear disclosures of such statistics collection now.
=> docs: mention `quickinstall` telemetry collection in `--help` and README

crates/bin/src/args.rs
If then default is too long, then users would still have to wait a long time if they hit rate limit.
=> reduce default for maximum_resolution_timeout to 15s

crates/binstalk/src/ops/resolve.rs
quickinstall telemtry is overloaded cargo-bins/cargo-quickinstall#268, it only needs report when the pre-built is not available in upstream.
=> Send telemetry report to quickinstall if no pre-built is found

crates/bin/src/args.rs, crates/binstalk-fetchers/src/common.rs, crates/binstalk-fetchers/src/quickinstall.rs, crates/binstalk-git-repo-api/src/gh_api_client.rs, crates/binstalk/src/lib.rs, crates/binstalk/src/ops/resolve.rs
similar to https://github.com/cargo-bins/cargo-binstall/pull/1905/files . I suspect that the discussions will be similar, but I won't push back on any changes you suggest.
* reports about all architectures on failure
* doesn't report whether the build-from-source fallback worked or not, because that seems basically impossible
* reports about how far each of the fetchers got (it does the fetch() -> bool for everything in parallel, and then tries the downloads sequentially. Knowing which ones were tried when they fail seems interesting to me.
* only reports about the winning architecture on success (I think this is fine: we can kind-of infer the status of architectures higher in the preference list, and we don't really care about things lower down)
Also it turns out this is my first pull …
=> report to new stats server (with status)

.github/workflows/ci.yml, crates/binstalk-git-repo-api/src/gh_api_client.rs
Fork cannot access secrets, so if that case that the token to empty and ignore it in tests.
=> CI: Fix binstalk-git-repo-api on PR of forks

crates/binstalk-git-repo-api/src/gh_api_client.rs
The client pool contains connections associated with a runtime when the runtime closes, the client may panic at seeing the connection disappear "abruptly".
Reported-by: https://archriscv.felixc.at/.status/log.htm?url=logs/cargo-binstall/cargo-binstall-1.8.0-1.log
Link: https://github.com/seanmonstar/reqwest/issues/1148
=> fix(gh_api_client): remote client should never being shared everywhere bacause the underlying connection pool will be reused.

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download.rs, crates/binstalk-downloader/src/download/async_extracter.rs, crates/binstalk-downloader/src/download/zip_extraction.rs
Fixed #1080
In this commit, binstalk-downloader is updated to
- first download the zip into a temporary file, since there is no correct way to extract zip from a stream.
- then use rc-zip-sync to read from the zip and extract it to filesystem.
=> Use rc-zip-sync for zip extraction

crates/binstalk-bins/src/lib.rs
Fixed #1943
The UI now looks like
```
WARN The package cargo-binstall v1.10.9 (aarch64-apple-darwin) has been downloaded from github.com
INFO This will install the following binaries:
INFO   - cargo-binstall => /tmp/e/bin/cargo-binstall
````
=> Improve UI orompt for installation

install-from-binstall-release.ps1, install-from-binstall-release.sh
This allow the users to choose different versions of cargo-binstall
=> install-from-binstall-release: Add BINSTALL_VERSION

install-from-binstall-release.sh
It appears that github API now enforces the user-agent
Tested here: https://github.com/bluerobotics/mavlink-server/actions/runs/11679849970?pr=83
=> install-from-binstall-release: Add user-agent into curl

crates/bin/src/gh_token.rs
Instead of using `gh` we should use the built in `git` credential helper to get a valid token. I think we could even get rid of reading the credentials files manually as git should be able to just do this for us.
What we're essentially doing is 
```
> printf "host=github.com\nprotocol=https" | git credential fill
protocol=https
host=github.com
username=3799140
password=TOKEN
```
Ideally we would even hand down a path so the token could be scoped to a single repository.
https://git-scm.com/docs/gitcredentials
=> Use git credential helper

.github/workflows/install-script.yml, install-from-binstall-release.ps1, install-from-binstall-release.sh
Github download urls for a specific release uses the pattern `../releases/download/[RELEASE]/..`, which differs from the latest release URL which uses `../releases/latest/download/..`.
For convenience, if `BINSTALL_VERSION` is set but doesn't start with `v`, the v is prefixed.
Fixes #1974
=> Fix installer downloads for specific releases

install-from-binstall-release.sh
This script would be useful to run in Docker containers, which don't always have `bash` available (e.g. Alpine). It just needs a few small adjustments to make this work, so apply those changes here.
Tested this script in an Alpine container.
=> Make `install-from-binstall-release` work with POSIX sh

crates/bin/Cargo.toml
=> Reduce log version requirements back to 0.4.22

crates/binstalk-downloader/src/remote.rs
This is for usage outside of binstall itself.
Sometimes it's useful to be able to specify more reqwest options, such as doing custom DNS resolution. This leaves the existing API identical but adds a couple methods that make it possible to construct a client with custom options.
=> feat(downloader): allow remote::Client to be customised

Cargo.lock, crates/bin/Cargo.toml, crates/bin/src/args.rs
Short help current look:
Uses the same coloring that cargo uses to make it easier to skim read the help
Wrap the help text:
Shorten the value placeholders:
Long help current:
Long Help Updated:
=> feat: add color and wrapping to help text

crates/binstalk-manifests/Cargo.toml, crates/binstalk-manifests/src/binstall_crates_v1.rs, crates/binstalk-manifests/src/cargo_config.rs, crates/binstalk-manifests/src/cargo_crates_v1.rs, crates/binstalk-manifests/src/crates_manifests.rs, crates/binstalk-manifests/src/helpers.rs, crates/fs-lock/Cargo.toml, crates/fs-lock/src/lib.rs
In case the unlock file, it might block cargo/cargo-binstall until the file is removed or kernel is rebooted.
So we should have logging for it.
=> Log when FileLock::drop fails to unlock file

crates/bin/Cargo.toml, crates/binstalk-downloader/Cargo.toml, crates/binstalk/Cargo.toml, justfile
Finally we don't need the external C codebase zlib-ng which is hard to cross compile
=> Use flate2/zlib-rs for dev/release build

crates/fs-lock/src/lib.rs
Likely fixes #2090
@dpc noticed in Fedimint that our locking was broken when upgrading from 0.1.8 to 0.1.9 of `fs-lock`. 
Looking at the [diff](https://github.com/cargo-bins/cargo-binstall/compare/f71ab715ab4c375693866343dd9e547e0252555d...b243c176fed21bae9ee5883deae97b7f500e5ae2) I noticed that a [version bump of the underlying `fs4` library](https://github.com/cargo-bins/cargo-binstall/pull/2072/commits/c836f0026a75938282d906b71e2fde0a4d91fc21) likely lead to the regression. The [documentation](https://docs.rs/fs4/latest/fs4/fs_std/trait.FileExt.html#tymethod.try_lock_exclusive) mentions that the `FileExt::try_lock_*` functions now return a `Result<bool, _>` where the `bool` indicates the lock status of the file, which is currently being ignored.
=> fix: actually check if lock was acquired

crates/binstalk-downloader/src/download/zip_extraction.rs, crates/detect-targets/src/detect/linux.rs
binstalk-downloader clippy warning is specific to windows
=> Fix clippy warnings for detect-targets and binstalk-downloader

Cargo.lock, crates/binstalk/Cargo.toml
Since we already use zlib-rs there is no point in pulling in zlib-ng
=> Use zlib-rs for gitoxide and avoid pulling in zlib-ng

.github/workflows/ci.yml, crates/detect-targets/src/detect/linux.rs
Fixed #2141 
On ubuntu 24.04, glibc are installed in:
```
/usr/lib/aarch64-linux-gnu/libc.so.6
/usr/lib/aarch64-linux-gnu/libc.so
```
=> Fix glibc detection on ubuntu 24.02

action.yml
Properly fixes #2157. The fix proposed in #2158 doesn't solve the problem.
The default command used by composite actions is `bash --noprofile --norc -eo pipefail {0}`, but if you change the shell to `sh`, the command is `sh -e {0}`, which does not catch the failing commands. See https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
Also added `--retry 10` to the `curl` command to make it safer.
=> Safer GH action execution for sh shells

crates/bin/Cargo.toml, crates/bin/build.rs, e2e-tests/self-install.sh
In v9 vergen is split into multiple crates with different git implementations.
=> dep: Replace vergen with vergen-gitcl

crates/bin/Cargo.toml, crates/bin/src/settings.rs
- atomically create the settings file using named tempfile
- use shared file lock when reading it
- read from the file when updating to prevent overriding previously saved data, and only update the `telemetry` field (since we only update it), plus use exclusive file lock
=> fix creation, loading and updating of settings

Cargo.lock, crates/binstalk-downloader/Cargo.toml, crates/binstalk-downloader/src/download/extracter.rs
- async-compression 0.4.19 => v0.4.29
- brotli 7.0.0 => 8.0.2
- bzip2 0.5.2 => 0.6.0
- xz 0.1.7 => liblzma 0.4.4 (a fork that is maintained)
=> dep: Upgrade compression libraries

crates/binstalk-downloader/Cargo.toml
#2303
After the change, https requests sent using `reqwest` will respect socks5 proxy defined in the `https_proxy` environment variable, e.g.,
```bash
https_proxy=socks5://127.0.0.1:1086
```
=> feat: respect socks5 in `https_proxy`

README.md
The examples given do not work anymore. This updates those examples in the readme.
=> Fix outdated cli argument examples
